<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Projet_AD_EMS</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="projet_files/libs/clipboard/clipboard.min.js"></script>
<script src="projet_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="projet_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="projet_files/libs/quarto-html/popper.min.js"></script>
<script src="projet_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="projet_files/libs/quarto-html/anchor.min.js"></script>
<link href="projet_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="projet_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="projet_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="projet_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="projet_files/libs/bootstrap/bootstrap-ab5a9f4898694041df425b902c4c541c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Projet_AD_EMS</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="quarto" class="level2">
<h2 class="anchored" data-anchor-id="quarto">Quarto</h2>
<p>Quarto enables you to weave together content and executable code into a finished document. To learn more about Quarto see <a href="https://quarto.org" class="uri">https://quarto.org</a>.</p>
</section>
<section id="running-code" class="level2">
<h2 class="anchored" data-anchor-id="running-code">Running Code</h2>
<p>When you click the <strong>Render</strong> button a document will be generated that includes both content and the output of embedded code. You can embed code like this:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell" data-tbl-cap="FAIS LE">
<div class="cell-output cell-output-stdout">
<pre><code>      age           gender        weight           height         bpm_ave     
 Min.   :18.00   Female:462   Min.   : 40.00   Min.   :1.500   Min.   :120.0  
 1st Qu.:28.00   Male  :511   1st Qu.: 58.10   1st Qu.:1.620   1st Qu.:131.0  
 Median :40.00                Median : 70.00   Median :1.710   Median :143.0  
 Mean   :38.68                Mean   : 73.85   Mean   :1.723   Mean   :143.8  
 3rd Qu.:49.00                3rd Qu.: 86.00   3rd Qu.:1.800   3rd Qu.:156.0  
 Max.   :59.00                Max.   :129.90   Max.   :2.000   Max.   :169.0  
    duration        calories            type          fat       
 Min.   :0.500   Min.   : 303.0   Cardio  :255   Min.   :10.00  
 1st Qu.:1.040   1st Qu.: 720.0   HIIT    :221   1st Qu.:21.30  
 Median :1.260   Median : 893.0   Strength:258   Median :26.20  
 Mean   :1.256   Mean   : 905.4   Yoga    :239   Mean   :24.98  
 3rd Qu.:1.460   3rd Qu.:1076.0                  3rd Qu.:29.30  
 Max.   :2.000   Max.   :1783.0                  Max.   :35.00  
     water       freq        level           bmi       
 Min.   :1.500   2:197   Min.   :1.00   Min.   :12.32  
 1st Qu.:2.200   3:368   1st Qu.:1.00   1st Qu.:20.11  
 Median :2.600   4:306   Median :2.00   Median :24.16  
 Mean   :2.627   5:102   Mean   :1.81   Mean   :24.91  
 3rd Qu.:3.100           3rd Qu.:2.00   3rd Qu.:28.56  
 Max.   :3.700           Max.   :3.00   Max.   :49.84  </code></pre>
</div>
</div>
<p>Il est essentiel de normaliser les données, car les variables n’ont pas la même échelle. Par exemple, la variable <em>calories</em> varie entre 303 et 1783, tandis que les autres variables quantitatives présentent des valeurs beaucoup plus faibles. Sans normalisation, la variable <em>calories</em> prendrait une importance disproportionnée et influencerait fortement l’analyse, ce qui biaiserait les résultats et empêcherait une interprétation équilibrée des données</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>respca<span class="ot">&lt;-</span><span class="fu">PCA</span>(gym,<span class="at">scale.unit=</span>T ,<span class="at">graph=</span>F , <span class="at">quali.sup=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">8</span>,<span class="dv">11</span>,<span class="dv">12</span>))</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>respca<span class="sc">$</span>eig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        eigenvalue percentage of variance cumulative percentage of variance
comp 1 2.926118302            32.51242558                          32.51243
comp 2 1.886427168            20.96030186                          53.47273
comp 3 1.271844140            14.13160155                          67.60433
comp 4 1.034764938            11.49738820                          79.10172
comp 5 1.007543322            11.19492580                          90.29664
comp 6 0.528664929             5.87405477                          96.17070
comp 7 0.322988781             3.58876424                          99.75946
comp 8 0.015430415             0.17144906                          99.93091
comp 9 0.006218005             0.06908894                         100.00000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(respca<span class="sc">$</span>eig[,<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_eig</span>(respca)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in geom_bar(stat = "identity", fill = barfill, color = barcolor, :
Ignoring empty aesthetic: `width`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projet_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>On constate qu’il est possible de conserver uniquement les quatre premières dimensions, car à elles seules, elles expliquent 79,10 % de la variabilité totale des données. Cela signifie qu’elles suffisent à représenter l’essentiel de l’information contenue dans le jeu de données</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>respca<span class="sc">$</span>var<span class="sc">$</span>cos2 </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Dim.1       Dim.2      Dim.3        Dim.4       Dim.5
age      0.005313815 0.001795596 0.01490023 6.195038e-01 0.336780057
weight   0.251556967 0.689499002 0.01241884 2.948873e-05 0.006017980
height   0.120009095 0.049006519 0.56178356 9.346186e-03 0.152948252
bpm_ave  0.024021638 0.025943921 0.15663385 3.808526e-01 0.392588829
duration 0.540535963 0.273427856 0.03084551 1.375423e-02 0.051162737
calories 0.670776262 0.209442703 0.06366851 3.295676e-05 0.012768095
fat      0.672092520 0.020931562 0.02477670 9.213223e-04 0.032153787
water    0.519724247 0.042137081 0.12784585 7.886467e-03 0.003807484
bmi      0.122087795 0.574242928 0.27897110 2.437898e-03 0.019316099</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>respca<span class="sc">$</span>var<span class="sc">$</span>contrib</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Dim.1       Dim.2      Dim.3        Dim.4      Dim.5
age       0.1815995  0.09518504  1.1715452 59.869036187 33.4258637
weight    8.5969513 36.55052335  0.9764436  0.002849799  0.5972925
height    4.1013070  2.59784845 44.1707862  0.903218305 15.1803152
bpm_ave   0.8209387  1.37529405 12.3154907 36.805711537 38.9649577
duration 18.4727994 14.49448251  2.4252587  1.329212574  5.0779690
calories 22.9237574 11.10261272  5.0059992  0.003184952  1.2672502
fat      22.9687405  1.10958758  1.9480926  0.089036867  3.1913057
water    17.7615596  2.23369774 10.0520060  0.762150578  0.3778978
bmi       4.1723465 30.44076856 21.9343778  0.235599200  1.9171483</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>respca<span class="sc">$</span>var<span class="sc">$</span>coord</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Dim.1       Dim.2      Dim.3        Dim.4       Dim.5
age      -0.07289592  0.04237448 -0.1220665  0.787085634 -0.58032754
weight    0.50155455  0.83036077  0.1114399 -0.005430352  0.07757564
height    0.34642329  0.22137416 -0.7495222  0.096675676  0.39108599
bpm_ave   0.15498916 -0.16107117  0.3957699  0.617132561  0.62656909
duration  0.73521151 -0.52290329  0.1756289 -0.117278411 -0.22619181
calories  0.81900932 -0.45764910  0.2523262 -0.005740798  0.11299600
fat      -0.81981249  0.14467744  0.1574062  0.030353291  0.17931477
water     0.72091903  0.20527319 -0.3575554  0.088805782 -0.06170482
bmi       0.34941064  0.75778818  0.5281771 -0.049375074 -0.13898237</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>respca<span class="sc">$</span>ind<span class="sc">$</span>coord</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Dim.1        Dim.2        Dim.3         Dim.4         Dim.5
1    3.186492134 -0.200615593  0.468630651  1.5227652590 -0.9014064034
2   -1.091808370  0.331504442  2.096919866  0.5274767111 -0.4930547207
3   -1.758870503  0.403545942 -0.082093570 -1.3428420433 -0.5621832038
4   -2.499658641 -0.226866136 -0.064932565  0.1957185218  1.9685814985
5   -2.095848411 -0.470600083 -1.430470181  0.9526165827  1.3391678617
6    1.161671020 -1.692833155  0.060583381  1.4712149443 -0.7971501644
7    1.267857359 -1.402380898  1.147743724  0.7509880480  1.2022190059
8   -1.185774599  0.019262652  1.913097634 -0.3151429598 -0.7428152904
9    0.235467962  2.903612328 -0.856098984 -1.1979328837  0.6474880215
10   0.016805335  1.822060860 -0.306860355 -0.8702875976  0.7252586148
11   0.645697218  3.669187207  1.068956761  0.2428329932 -0.3930477459
12  -0.041169901 -0.911398898 -0.979336655  1.4553861506 -0.4006297491
13   1.433635308  2.221549721  2.401652706  1.8344580067 -0.5670297773
14   0.890455680  1.434141211 -2.284687210  0.2260826170  0.4698353384
15   2.247701714  1.819471547  1.068372915 -0.4171763323  1.8648137366
16  -1.723311866 -1.436686374 -1.267938389 -0.4362086645 -0.2683889883
17  -0.297144492 -0.896176518  2.353596308 -0.4800098176  1.4797892829
18  -1.922382237 -1.910403213 -0.007637690  1.0746468843  1.4146420800
19  -1.298134739  0.019514777 -0.363299605  0.7326397514  0.0767255431
20   0.132168080 -0.387965957  1.232025523  1.8638528025  0.0654053471
21   1.364430748  0.757669234 -0.417695071 -1.8643661442  0.2328013419
22   0.031926475  0.173037961 -0.752206015  0.0507585190  0.1831908351
23  -0.950609732  0.044486248  0.708758398  1.4661905102  0.3453698770
24   0.718189768  3.289295568  0.824661911  0.6357555781  1.8330184697
25  -0.863392674 -0.712013269  0.497000665  0.1000862432  0.2266456747
26  -0.263681708 -1.345221243  1.065541106  1.1209475774  1.0121957459
27  -1.680145259  0.639780416 -1.504011486  0.4376079910  0.0797082942
28   0.224220040 -1.381441320 -1.142178361  0.9312196589 -1.4100654151
29   2.557102127 -0.095356593 -1.301167316  0.1176589197 -0.7379598541
30  -1.122161725  0.270002381  0.856126845 -0.8807399901 -0.0258241389
31   1.316600015  1.999545452 -0.058563200 -0.5440080869  0.2748351652
32  -1.631553577  0.377932788  0.993686558 -2.0366528488 -0.3875271005
33  -0.313929898 -1.693154723  0.523805455  1.4438849078 -0.4701639046
34  -1.413338121 -0.333008086  1.601250610 -0.4461726093  0.8612418073
35   2.861978089 -0.323708307  0.017021256  0.0642068498 -0.4027220514
36   1.990416424  2.568629533  2.115318911 -0.2322162839  1.2617030281
37  -1.171417307 -0.549803341  1.043371942  1.4980810117 -0.6412935096
38   1.215705974  1.066084601  0.825127879 -0.2524814560  0.0655698374
39   0.666234891 -0.777574794 -0.852521721 -0.6283685955  1.4831617791
40  -0.130084920 -2.010954110  0.534598239  0.9519011974  0.2874531962
41  -1.140541494 -1.616986384  1.055569014 -1.3071849315 -0.8225091914
42  -2.548969558 -1.184090522  0.214800834 -1.1449833650  0.3275965554
43   1.067531808  1.952112210  0.071698576 -0.1366597834 -0.3350174484
44  -1.602293145 -0.226863247  0.490855913 -2.0011584318  0.0094396078
45   2.113885348  1.979345762  1.914373270  0.3554065318  0.7917598964
46  -0.390371297 -1.398746122 -0.985454371  1.3014790945  1.0380347812
47  -0.162525212 -0.485512942 -0.821612616  0.3921107370  1.8939493342
48   1.295152641  0.367768210 -1.518593929 -1.2418670151  0.7177370819
49  -1.664031074 -0.702218845  0.212333949  1.1429332021  0.0050835457
50  -0.846016430  1.034533585  1.637770405 -0.6390527172 -0.1778316407
51  -0.560459673 -1.768873273  0.933690706  0.2092630797  0.7311405917
52   2.643899875 -0.103047124 -0.638520315  0.5575187431 -1.4847141998
53   1.158162447  3.095558656 -1.042089484  0.9947030016 -0.8125537618
54   1.029678288  1.056671581  1.027278273 -0.8609438475  1.1069447552
55  -2.211278375  0.761858604 -0.716700900 -1.9571241390  0.6760656998
56   2.454992087  1.688985612  3.165032810 -0.5150992243  0.8718133944
57  -0.751019369 -0.633993470  2.100546300  1.7912993295 -0.7061898576
58  -1.539250726 -0.915852871  1.166330346 -0.7214071613  0.9410489676
59   1.260151466 -1.636183033  0.071228239  0.7114167332 -0.3296843167
60  -3.413629675 -0.426743698 -0.004646317  0.5026363507  1.0377039549
61  -1.581516016  0.035490154 -0.501925567 -0.5415520377 -1.3638666824
62  -2.569422182 -1.020332324 -0.296560555  0.5232703261 -0.7775672812
63   3.122387953 -0.036195707  0.815254544 -1.3489163498 -0.8225824661
64   0.097101799 -0.683435665 -2.050122564  0.4261353114 -1.5271346120
65   2.215771868 -2.067797697  0.497262399 -0.7501851994 -0.1575930402
66  -3.314667235  0.870846018  0.814206536  0.9091797614  0.0580624888
67   3.801688164 -0.729168944  1.589086982 -0.7135016478 -0.7280257365
68  -1.303209528  0.257390246 -0.838468113 -0.7822579643  0.9305608995
69   1.819101108 -2.074475423  0.043327541 -0.3708941853  0.4454617770
70   2.426580818  1.645246991  1.611993720  0.7850509349  0.1899960170
71   1.037785082 -0.931353286  0.719748194  0.1733606101 -2.7821537193
72  -0.520529442 -0.596631314  0.885849602 -0.7590717900 -1.1099137645
73  -2.630094245 -1.721748975  0.342937679 -0.2801829558  0.5939794292
74  -1.111316354  0.234949633 -0.981831068 -0.9253601426 -0.2183190760
75   0.484229281  1.788882826  0.813101099 -0.1092120462 -0.8479954167
76  -1.203243108 -0.649394796 -1.745238920 -0.4755820260 -0.7248283558
77  -1.514961321 -1.379150941  0.047858856  0.0245158191 -0.0194187711
78  -2.669422933  0.871864091 -1.258982801  0.7098083502 -1.2002944949
79   1.080827121  1.719262854  0.207806503  0.6586241529 -0.1917090023
80   1.656710646 -1.727952172  0.862784417 -1.1403812185 -1.0424688179
81  -0.859116347 -1.524793890  0.342783588 -0.3657220957  2.2822126432
82   1.396283333 -1.773390407 -0.433741762 -0.0622572153 -0.6718625518
83  -2.416879323  0.702444113 -0.326148028 -1.5999141575  0.5006000919
84  -1.163044549  0.463468577  1.066514700 -1.1756388980  0.2051941376
85  -0.080064328  0.219967780 -1.450894807 -0.1492458342 -0.2904436674
86  -0.986572640 -1.343659726  0.747207993 -0.7342972187  1.7923301790
87   1.531995393  0.816507655  0.415819818 -0.3753981095  1.6540867159
88  -0.787775450 -1.628294690  1.990019732  0.9761937616  0.6371605498
89   1.016011910  0.741505206  0.385808269 -0.2096000740  0.5456868397
90  -1.996205645  1.749092191  0.047232700 -0.7577715452 -0.5275817744
91   4.182944873 -1.266641911  1.748336556 -0.5411433057  0.2506313039
92   1.710050160 -1.850389202  0.221242847  0.9741656500 -0.8489600844
93   0.694984844  0.351736396  0.199077156  1.1775208051 -0.7832034305
94  -1.145465785 -0.885870042  1.034924161  1.4967076392  0.1600524998
95   1.509946212  1.067656964  0.254796052 -0.6402624349  1.4748107892
96  -2.721745068  0.183078438  0.525585871  2.4799845135  0.0621196126
97   0.920275871  3.283336720  0.422052102  0.2740464914 -1.5585232098
98   1.590478062  1.450090218  1.714681754  2.1449699378 -0.2329943837
99  -2.101179475 -0.273628142  1.397027776  0.1360793754 -0.7961076730
100  2.819228710 -2.834713871  0.475981168 -0.2236974190  1.4668569906
101 -0.424198222  0.884625167  0.339102968 -1.5585294806 -0.4527408542
102 -0.930995553 -2.390356158  0.470686231 -1.0006946505  0.5011022896
103 -1.130533672 -0.611751683  0.094314672 -1.6772964856 -0.8243641468
104 -0.647023612  3.420585157 -0.241632547  1.6733525737  0.4039780185
105 -1.226277685  0.147150313 -1.931785458  0.7578985444  0.2772322360
106  1.790344388 -2.366830839 -0.318012524  0.3692243089  0.2568526257
107 -1.748442802  0.952915847 -1.728981837  1.6491228894  2.1628723630
108  3.530049807 -0.793562322 -0.918903862  1.8484757263  0.2790460447
109 -0.406435964 -0.136090713  2.312010900  1.3091598144 -0.1932511386
110 -1.644316326  0.924634728  1.050985998  1.3003356118 -0.7178117689
111 -1.063557556 -1.415300456  0.844975965 -0.5776250383 -0.6738043264
112 -1.130592690 -0.301406812  0.681258018 -0.4329444458 -1.3843511357
113  3.196558500 -0.606020019 -0.335497457  1.2360095613 -0.4005358259
114  3.434878893 -0.493018135 -1.253039471 -1.4547334692  0.8884463457
115 -0.485578679  1.124770745 -0.368634625  0.6298657291 -0.9178806531
116 -1.352096088  0.840925483 -0.423263177  2.0590831712  0.1518745095
117 -1.499176722 -1.899910222  0.736679193  0.2545452518  1.0677521927
118  3.247873806 -0.800577232 -1.539335097 -0.9441843479  1.4325623718
119  2.187075764  0.164423739  1.231257357 -0.3302348171  1.9512167120
120 -1.259222707 -0.101193913  1.464960496 -0.6604169147  0.9091648899
121  0.231835255  0.646871639 -0.990457479  0.3951961413  0.2027725970
122  0.907354929  0.578807672  0.207181346 -0.0778300186  0.8664316393
123  1.064213215  3.628921663 -1.588319352  0.7842300532 -0.7831283363
124  0.976907344  1.613866630 -1.026684855 -0.0781178540 -0.6443428071
125  4.204389206 -1.119802733  1.367032942 -0.5069962296  0.4131854271
126 -0.074418434  0.760590233  0.353451897 -1.2495958228 -0.8427177107
127 -3.138078279  0.389889856  0.290759300  0.4145330886  1.3936040600
128  2.303774284 -2.748125417  0.183635045  1.0419893645  0.6035814665
129  0.455334855  3.536000599 -0.907009951  1.9809147953 -0.0324250103
130  3.539376697 -0.698189038 -1.195439782  0.0369800079  1.1439319665
131 -1.532708236 -1.668082064 -0.347092189  1.2236442201  0.4153930523
132 -1.795398102  0.425683574 -2.982219651  1.3028060646 -0.1584161636
133  3.749350632 -1.234352730 -0.993821759  1.3341600109  0.3881005745
134  2.257309234  2.684367856  2.541233210 -0.6006415856  1.1742727994
135 -0.901488354 -0.843420451 -1.020323650  0.0297302092 -0.6231670889
136  0.428226286  0.971058256 -1.975472241  1.1543569501 -0.0833089465
137 -1.303980241 -0.932128318  1.736190536  0.5199831917  0.5944192216
138 -2.271482198  0.989743392 -0.451820553  0.9692094725 -0.9106896573
139 -1.389652569  0.149959514  0.565229047 -1.5308675295 -0.8645738153
140  0.962454013 -1.404202288 -0.017127996 -0.0258078645 -1.3100949499
141 -0.096555212  1.983764752 -2.160898556  1.1050286416 -0.0276994184
142  0.174653029  0.099143857  1.802375470  0.2646497545  1.1321934789
143  1.065312915  2.293089146 -1.057358308  0.0049400704 -0.7637410569
144 -0.320650094 -0.918769270 -0.515776282 -1.3052269490  0.6053253283
145 -1.008279000  0.322711397 -0.733112713 -0.5377487743 -0.8939487173
146  3.001486061 -0.157858357  0.189285666  1.3730756870  0.4203846995
147 -0.553975207  0.085675124 -0.161031762 -1.4676862360  1.0028364926
148  0.070200797 -1.076421320 -2.250684456  2.7076118973  0.9162780419
149 -0.747114316  1.386431381 -0.359904834  0.1071420442  2.1176460202
150 -0.321731304 -1.002200052  0.160612105  0.9918813394  0.6887655940
151  0.339998195 -2.428823722 -0.251474477  1.4417815241  1.0347997748
152 -0.429415627  2.625146336 -0.717431322  1.3310013704  1.9647727284
153  1.479401373 -1.542908152  0.877706126 -0.4217492389 -2.1835533966
154 -0.738754903 -1.753582038  1.303387123  0.0319374722  1.2446964003
155 -0.511697264  3.232849302  0.456742627 -0.2448452819 -0.9947291832
156  0.305141510 -0.474854217 -2.751579112 -0.2071406691 -0.0949240932
157 -1.422723203 -2.043921080 -0.683937016  2.1118139756  0.6930910925
158 -2.492914943  1.265062152 -1.666882772  0.0092409674 -1.1023770482
159  0.625469216 -0.788342912  1.798146827 -0.4316052665  1.7116558278
160 -1.241453030  0.061076334 -0.021861712  0.8703171355  0.5545633326
161  0.240545274  2.486653045  1.340699114 -0.7626424065  0.0821877636
162  1.291780988  0.950939046  0.221284538  1.6989029829  0.2330180936
163  0.957987407  0.974839318 -0.266629105 -1.1143478745  1.5829347215
164  2.827328342  0.072040277 -1.132316279  1.1452515284 -0.9960523703
165  2.536174769 -0.145832466 -1.169953834 -1.7362714677 -0.3884284506
166 -2.324774079 -1.622890164  0.811537960 -0.1521320420  1.5964010115
167  0.496515252 -1.071318708  0.807554846 -0.2734908165 -1.6591487212
168 -1.617741135 -1.022982277  1.426205072 -0.8371659751  0.3657773037
169 -0.881355025 -0.259069499 -0.001498961  1.1424902059 -0.1549340887
170 -1.817682251 -0.361446196 -3.055362109  0.3528850155 -0.1673122538
171  0.410526465  1.307900552  0.010490172  1.7374576584 -0.6625269233
172 -1.689981979 -0.777284793 -1.540634880 -0.4833584570 -0.4218580493
173  2.938824475 -0.069186391 -1.118978894 -0.3745569288  0.2914817275
174 -2.339698206 -1.132079552  0.029009042 -0.0064082144 -1.5360006294
175  0.376653772  0.458947676 -0.446107828  0.0243261838 -1.2575094105
176 -0.301502285 -0.171970469 -0.780546618 -0.3449628607 -0.7840459462
177  1.146639732 -1.387603338 -0.527773104  1.6051082314 -0.5868142441
178 -2.723202120  0.495104426 -1.701908250 -1.1633215764  0.2018469025
179 -1.425733271 -0.881994484  0.126459635  1.5773639642 -0.4043973146
180 -1.519941881 -1.061812595 -0.226779270 -1.0162916177  1.2710339423
181 -0.062460914  3.603589014  0.189605397 -1.5980869152  0.8857258565
182  2.507751247 -0.082560187 -1.370759043  0.9721215738 -0.8957291007
183  1.534310925 -2.131975843 -0.595684293 -0.6702779543 -0.2519177922
184  1.555615602  0.351420646  0.370631879 -0.4241361064  1.8231207252
185  3.476548163 -0.697907197 -0.241548206 -0.7198153745  1.4108719280
186  0.738197101 -1.677346584 -1.423092824  1.2463863905  0.8270969001
187  1.671397721 -2.216532527  0.032034350 -0.1519086356 -0.5075910006
188  1.020430444  2.159573208 -0.938895228  0.6903409061 -0.6120003853
189 -1.186027830 -0.916285235  0.869421487  0.8487136245 -0.1123226362
190 -1.191100100 -0.353862503 -2.294930405  0.4826190105 -0.2405938666
191  0.335289118 -0.193443522 -0.694446094 -0.6841696732  1.7348572275
192 -0.512572816  0.106587989 -0.064153257 -0.9476037074 -0.8438708715
193 -1.166042804  0.030695721  1.231759488 -2.0013297257 -0.2256770220
194  0.533466900  1.673618819  1.443258387  0.3801700962  0.1091685912
195 -2.378970382 -1.267719565 -0.495249177  0.9705265727 -0.1006026435
196 -3.471376081 -0.456112321 -0.405676840 -1.3997823927  0.2232505974
197 -0.799989206 -0.490259903  2.100539250  0.5702812797 -0.8395751586
198  2.804787739  0.409629187  0.628433599 -2.3443624939 -1.3346484419
199  0.540458334 -0.676229867 -1.136966389  0.1790813532  1.8141452959
200 -0.190013266 -0.167261180  0.568586954 -0.8810252405 -0.5434145034
201 -1.500424469  0.709889408 -0.243432251  0.4426870992 -1.2236683173
202  1.867807539 -1.757797829  1.163776074  0.2009455866 -0.6751588487
203 -0.089455981 -1.041796236  0.978970870 -0.5862193147  1.7867228158
204 -2.167649072 -0.202574962 -1.311581588  0.0122101499 -1.0351178104
205  3.425916708 -0.685029714 -2.030916275 -1.4820559539  0.3913659570
206  1.864701696 -2.543254675  0.270577691 -0.0231732104 -0.2118065284
207  0.325882705  1.312709552 -0.870496855 -1.4763217325 -0.3864397630
208 -0.991863137 -0.149929380 -0.272342637 -0.6884757361  0.0252096158
209 -0.069257488 -1.981241046 -0.142051201  1.3318589253 -0.0514776245
210  3.214254716 -0.300509783 -1.168580923 -1.2956149080 -0.0540620640
211 -0.409361572 -0.573331652  1.571366098 -0.6904712272  1.5732814873
212 -0.931572030  0.593742940  0.155884368 -0.7205229251  0.0088079622
213  1.131094945 -1.689055536  1.040481682 -0.0514932563 -1.6243034859
214 -0.502069275 -0.448652900  1.282160648 -0.4156843589  1.9301798304
215 -0.720661709 -1.173069145 -1.107988164 -0.2345120126 -0.0310992980
216 -1.863738876  0.692484224  0.670701737 -0.0231898295 -1.4572479015
217 -1.174178475 -1.028431154  0.817972127  0.2825582153  0.6357097955
218 -1.976543112 -0.954373792 -0.228793585 -0.4608182053 -1.0449550869
219  0.511266830  0.074549129  0.752889973 -1.8478153196 -0.1519692605
220  1.526189500  1.991366192  0.658110369  0.4381376817  0.7793751768
221 -1.200917097  0.212478064 -0.561922796 -1.1066607619 -0.6663868285
222  3.581899448 -1.144894208 -0.405322124  1.3088573686  0.1281824729
223 -3.063400960  0.363743347 -0.973418782 -1.3305672605  0.7286733238
224  2.695414627 -0.259172146 -1.486649971  1.2623914013 -1.0594888523
225  0.639450531  1.282465939  0.174974720 -0.1935263483 -1.5624545190
226  3.191992914 -0.766680892 -1.096980506  1.2011851004 -0.9980562439
227  0.042019326  2.618285156 -0.003881374  0.3583660179 -1.6355984908
228 -2.158149103 -0.178188943  1.469806275  0.2594041408  0.9371031315
229 -1.137196695 -0.390761026  1.463338154  0.5820622996 -1.6104873137
230  1.557917709 -1.449502442  0.659254438 -2.4494928333 -0.8302383500
231  0.400428950 -0.105039790  1.504830656 -0.0557997184  0.9212179727
232 -1.614690056 -2.085872656  0.483816258  0.4113985752 -0.0960275183
233 -1.145288913 -1.651566144  0.095978150  0.9708655076  0.9908573589
234  1.133298518 -1.926064051  0.754394054  0.5003054876 -0.0783763721
235  0.648903714  0.539391034 -0.419724260 -0.3871010372 -2.1468442442
236 -0.439486933 -0.762276469 -1.306272248  0.4339636609 -0.4644124093
237 -0.443650258  1.506110552 -0.980713223  0.5531017703 -1.6899074583
238  0.592855051 -1.046830979 -0.745413123 -0.0953197847 -2.0325491128
239 -2.127646073 -1.807687509  0.638885792  0.1253538858  1.9752699984
240 -0.719037074  0.025948268  1.605527574  0.0007694576  0.8713498999
241 -1.023976238  2.358721199  0.811370482  0.4047517037  0.1252597375
242  1.761684801  1.424284867 -0.135653233 -0.9288092007  1.7143296623
243 -1.678500493 -0.293706995 -0.898639517 -1.9637242143  0.7297806397
244 -0.768762382 -1.135447633  0.358289759 -1.4200908907 -0.4901871957
245  1.777464806  1.848089161 -0.841575734 -0.8422707801  1.2967660923
246 -1.481964148 -0.103628824 -0.973934163  1.5539313025 -0.1992390125
247 -0.605819133 -1.447757102 -1.477132589 -0.3418788981 -1.6423319578
248 -2.402224914  0.845159523  0.069546107 -1.6097313587 -0.0981225821
249 -0.322961626  0.557750195 -0.889539652  1.0610685237 -1.1235784096
250 -1.515100711 -0.516920285 -1.984440559  0.5235833069 -1.0978940778
251  1.437630446  0.684368858 -0.996878710  0.0903577302  1.0910188160
252  0.248158451  3.246333256  1.815517162 -1.1421558893 -0.8341551396
253 -0.197505475 -0.378841042  0.958129660 -0.9351464176  1.4554294661
254 -1.896607898  0.446630421  0.296898871 -1.2419869875 -1.0160386680
255 -0.550648520  1.113891714 -0.662368129 -0.1985048061 -0.5696682384
256  0.050560987 -1.488429218 -0.357683100  1.2993877643 -0.1024980236
257  2.610976791 -0.305835107 -0.671491399 -0.0856002967 -0.6591754994
258  0.435546942  1.799799003  0.238523656 -1.8100535596 -0.3921578855
259 -1.179623512 -1.062146094 -2.583416127 -1.5388055071  0.7433012402
260 -0.614723438  4.234193875 -1.334191535  1.0256283096 -0.1084390974
261 -1.073224667  0.587187564  1.128149949  1.6233036014 -0.0957966526
262  0.251118784  3.879836972  1.732966214  0.4687469434 -1.8858697946
263 -1.051047844 -1.115647638  1.043745959  0.0495455491  0.0959137343
264 -1.648241358 -1.513557292  0.939814107  0.7357782699 -0.9418142349
265 -0.262964522  1.814374693 -1.246538294  0.1335214601  0.2899276266
266 -1.318434506 -0.819935547  2.210161786  1.4887287413  0.0006030633
267 -1.152687062  0.356101046  0.287491169  0.4011513620  0.1043481999
268  0.920605089 -1.500017410 -0.028958362  0.8415922353 -0.2293858567
269 -1.879088654 -1.100869212  0.782744216  0.2284310037  0.6551849558
270  1.338986027 -1.298363318  0.912902921 -0.4422940596 -0.5991707121
271 -0.587573621 -0.931274305 -0.525055755 -1.4969756155  0.9549208446
272  1.080737209  2.097470256  1.400119959  0.5945566116 -1.3012265560
273 -2.726798151 -0.947042907  1.012002226 -0.4707888446 -0.0541357568
274 -1.652233808  0.204310076 -0.277395526  0.1630962640 -2.1709538199
275  0.705521289 -1.453883034 -1.204437465  0.7813577370 -0.9044533149
276 -0.852514284  2.116914046 -0.576710853 -0.0241142484 -1.4796864219
277  1.510733836 -1.890641816 -0.184258648 -2.2492653123 -0.6151180430
278  0.667921430 -1.852581668 -0.322644274  1.1844211101 -0.2124901995
279  0.548272780 -0.863747820 -0.110248842 -1.4449373142 -1.0544188231
280 -0.239570406  2.030835230 -0.763661915  0.0769541976  0.1385222768
281 -0.294691627 -1.452295758 -0.640601423 -0.5649981730 -0.5464793286
282 -1.066306068 -1.361586961  1.913652788 -0.6238445757  0.8799318574
283 -2.514833731 -0.958501155 -1.064309967 -0.6784452646  1.2895463047
284 -0.575183788  3.621189320 -0.139078409 -0.9411326178  1.8774458444
285 -0.005835720 -0.357243048  2.149900867  0.0798430731  0.4787109867
286  3.125373201  0.040329798  0.322682540  0.3119801662 -1.6298108398
287  2.337988037  2.002243353 -0.471253907 -0.0935525479  1.6893666094
288 -0.460687572  2.342455994 -1.750163674 -0.1119835884  0.6298349477
289  0.600881459  1.088846429  0.938072262  0.4347011177  0.3408537590
290  0.960871072  0.449746328 -1.239935782  0.3613537239 -0.4943808840
291 -2.809778152 -0.754828982 -1.010898854  1.0735217822 -0.5500766652
292  1.599698706  3.110229601  2.167208562  1.7564135030 -0.2470749167
293  1.548997005  1.371741290 -0.619882437 -1.1902224813  0.9589888251
294  0.157697334 -0.417628693  0.573942542  1.1886269712  0.9959756278
295  0.183516883  0.336938501 -1.297259153  0.0455679714  0.3077663372
296 -0.941816540 -0.249085264  1.570352768  0.2300613370 -1.3917816758
297 -1.898757389 -0.647897388  0.160386748  0.1337836760  0.6088544777
298 -0.939907507 -1.898374423  0.214150657  0.4947195071 -0.2785410489
299 -0.901202017  3.357532656 -0.329753597  0.1558032095 -1.4701575493
300  0.535274561  1.626570699 -1.683980715  0.7465874025  0.3287562169
301 -0.816039308  2.369732748 -0.155269208 -0.1306497454 -1.9632027107
302  0.863860598 -1.813465089  0.622856512 -1.2440852250  0.1825882148
303  1.353818524  2.589226243  1.841966303 -0.7003115069 -0.4956267076
304  2.200121660 -2.233333811  1.656673480 -1.1536557041  0.2436297910
305  0.647026057 -0.207216267 -2.380293735  0.0403110362 -1.1325411586
306 -0.772865881 -0.116428992  1.519055909 -0.9817860864 -0.8154221583
307 -0.937499285  0.890739811  1.148664283  0.1546430545 -0.6529752230
308  2.886783356 -0.362345830 -1.329788876 -0.1224389923 -1.2379371516
309  0.832920887 -1.090311613 -1.229790648  0.2879569287 -0.9024296531
310  1.326922662 -1.783629804 -0.527186508 -1.1896985957  0.5041978089
311  1.821968921 -1.657064559  2.158899060  1.3389869952 -0.8538430801
312  0.807609033  2.135199734  0.944495247  2.2660754190  0.1705324128
313  0.104750309  1.206071580 -2.319336510  1.5185313056 -0.0538795950
314 -1.046462516  0.113982495 -0.177309926 -0.3890151850 -0.1887528140
315 -2.073569050  0.067799867  0.776347291  0.8115398339  0.0385046879
316  1.164105878 -1.396353026  0.487570181 -0.6102845448 -2.3268606495
317  3.178196601 -0.466135550  0.009631433  0.7534693717 -1.1701984689
318 -1.923367961 -0.055764306  1.063660818 -0.0171349811 -1.3532290286
319  0.674975930 -1.166555248 -1.840201722  0.2808299006  0.9743836187
320 -2.103294094 -1.359453603 -0.471015922  0.1417814387 -0.9975271609
321  0.793021701 -0.525165579  0.027930612  0.0573480531 -0.6121276114
322  0.723036910 -1.576145431  0.225929692 -0.5342427738 -2.5774683037
323 -0.959309102  0.397364484  1.970021597 -0.3115339473  1.6902941176
324 -0.574696197  0.293408692  1.365044646  0.7916889786  1.3727320734
325 -1.672399786 -0.523610157  0.148480366  0.4810962870  0.2413299988
326 -1.703793987 -0.179427825 -0.352219976  1.8705739776 -0.1135869436
327  0.233564464 -1.092150855  0.870221036  1.4995133126  0.8098385574
328 -0.268114567 -0.257650828  0.034125358 -1.7289355382  0.6633095697
329 -2.555603616  1.668493423 -0.056837526  0.7180320975 -1.3583595300
330 -0.526775531 -0.275794444  0.992343827  0.1368838310 -0.1543993415
331  3.688103478 -0.761833791  0.970210238  1.2577205239 -0.4682336976
332 -1.298403837 -0.278312006  1.305511675  0.0980758212 -0.0630041232
333 -1.070421761  0.388655974 -1.228531571  1.1971642699  1.8618560855
334 -2.415583066 -0.898372043  0.869145959 -1.7329979151  0.2018881177
335 -0.079175754 -2.326218207 -0.661035655  1.0319599643  0.6346790805
336  1.061273045  0.354648748  0.598995974  2.3426835516  0.2280600281
337 -1.268660124 -0.118168617  0.388548761 -1.4660911891  1.1525896775
338 -0.035178281  0.297449920 -1.564841796  0.4974663439  0.3632121187
339  2.338066120  1.623262707 -0.476874604 -0.3873585613  0.2126569049
340 -1.378851186 -1.760060931 -0.990327878  0.4982234555 -1.2759023850
341  0.745571822  1.405616149  0.076858509  1.2174042845 -0.3036929434
342  1.145260643 -1.377513905  0.966295482 -1.7830526272 -1.2676661734
343 -2.171523185 -0.470016770 -1.898281630  0.7105399754 -1.2225609491
344  0.584959397 -2.048842403 -0.832223929  1.4363281598  0.6927215167
345  1.121967569  1.326853183  0.124771701  0.4268113402 -2.4929401268
346  1.416288348  3.274263342  1.808048874  0.6428773796 -0.0198891233
347  0.326972375 -0.298528311 -0.254224041  0.7744531724 -0.8247782263
348 -2.412908839 -0.962106141  0.909057106 -0.5772191021 -1.2500743866
349  2.273937724 -2.405244431  0.244887572  0.7359353267  0.5263217577
350 -2.032540553  0.424485524 -1.549322455 -0.3215533296  1.2132784137
351 -0.621403433 -0.668803898  0.541931858 -0.9110597880  1.1369704324
352 -0.592872569 -1.556523550  1.508141950  1.5368982604 -0.0952462934
353 -1.524981977 -1.285124765  0.287505742  0.3790339721  0.8963078930
354 -2.172028073  1.146111689  0.931181230 -2.1960683305 -0.1585189721
355 -1.485253139  1.226936298 -2.549592961 -1.5119439528  0.6301154372
356  1.503839871  1.983269544 -1.590514850 -0.9073257280  0.2906764950
357  1.639115959 -1.736604389  1.338268009  0.3735370025  0.8532266859
358 -1.095704702  2.177439945 -0.927134167 -0.4494965542  1.0777465732
359 -0.449102363 -0.841965237 -1.411412000  1.0759690683  1.1012618601
360 -0.855141239  3.306624495  0.575876075 -0.3086855713  0.2600567981
361 -1.423542774 -0.296022602  0.964648309  0.2342382934 -0.1521831868
362 -1.622052087  1.636167469  1.145052412  0.2878078691 -1.5837269333
363 -1.435645968 -1.305862554  0.186639729 -1.2073406346  1.1521940307
364 -1.976607199  1.092516376 -2.278639622  0.3250560502 -0.3045918736
365  1.842002517 -1.828824956  1.551690887 -0.3610855867 -1.2132728897
366 -1.749303675 -0.523805233  0.977992137  0.9654656026  1.1159877401
367  0.299839304 -0.036190594 -1.450331944  1.0181335062  1.3036148320
368  1.417318343 -1.545801252 -0.354047835 -0.9923700336 -1.3320506322
369 -1.181397303 -0.669895460  1.587006826  0.2328526581  0.4749022599
370  1.694413144  2.098509740  0.451008325  2.0217382627  0.2103070925
371  1.213217455  1.623057515 -1.319032161 -1.8729499937  0.2836889202
372  1.313592204 -0.978858524 -0.886109335  0.7562385685  2.0588763404
373 -1.252657886 -1.366448492  0.319743312  1.3908050901 -0.5024073074
374  0.727213707 -1.319835923 -1.336059142  0.1381393372 -1.2504054684
375 -0.036132153 -0.808913997  1.362143274 -0.5321137625  1.2776123090
376 -0.325903310  2.230762629 -0.055030431 -1.5740038801  0.6733431403
377  1.332865758  2.918023079  0.142606393  0.4960889125 -1.4037402660
378 -1.096835954 -1.581239287  2.108197570 -0.6494312292  1.3293742923
379 -0.430443428 -0.831414419  1.434093626 -0.0865923779  2.0424744712
380  0.036734212  0.891950044  0.662437979  1.3351563842 -0.2275344612
381  2.803538334  0.278197338  0.654941724 -0.5207901081 -2.3783329988
382 -0.548571201  2.060706255 -1.685758068  0.4640992631 -0.2110244991
383  0.540989014  0.815233642  0.121381506  1.7347446868 -0.5428185171
384 -1.995061077  0.204157944  0.023437546 -0.0298154064  1.0257866287
385  2.162029635  0.411977334 -1.523778189  0.1081732784  1.5469718487
386 -2.266888981 -1.343101054 -0.663934709  0.8083527279 -1.3955735924
387 -0.499249010 -0.312620866 -0.468106954  0.2343733083 -0.5359222132
388 -0.966798080 -2.415227503  0.606691339  0.4010237140  1.2571059335
389  0.060569909  2.114953571 -0.787564598 -0.0444436035  0.3072544011
390 -0.003285469 -0.428889895 -2.994424519 -0.4304844961  0.1836968124
391  0.279987050 -0.958399501 -0.531611534  0.7468331597 -0.0860675531
392  3.876893854 -1.268140492 -0.948263452  0.9916212539  0.6839368170
393 -1.364639824 -0.059906392 -0.599006041  0.3381205469 -1.1666290849
394 -0.466265336  0.196092081 -2.128502307 -0.4265376301 -0.7379997384
395  1.126461715  0.046023840 -0.101887050  0.6390732847  1.2333913915
396  1.937936034 -1.584885110  1.603801195 -1.6796423466 -1.1843669139
397  2.154544773  0.662262569  0.224116741 -1.6920378346 -1.4547978640
398 -1.002371178 -0.788814361  1.708881146 -0.6517259459  1.6696306274
399  2.151012570 -2.396872186  1.137374322 -1.3750203153  0.4123958218
400 -0.850286788 -0.294553496  0.312677812 -0.1698812327 -1.8113687537
401 -1.793717906  0.423171526  0.180751014 -0.3940832176 -1.6536915738
402 -2.955765964 -1.160016204 -0.986130937 -0.3047728811 -0.2415809872
403 -2.251948112 -0.816757153 -0.064645656  0.7012552191 -1.2683461455
404 -2.401395652  0.882196398  1.059286534 -0.3213868923  1.9632036887
405  1.358900735 -2.128594766  0.770854605 -0.4775659382 -0.2826710567
406  0.207783395  3.208514692 -0.356054570  0.5014155990 -1.0562218088
407  1.422190476  0.515829326  0.883388397 -0.5494456171  1.8773831156
408  0.243007453 -1.401973032  0.331003711  0.9631854439  1.2859073897
409  2.495863171  1.625425278  2.013118635  1.3865586893  0.1116018160
410 -3.325439625 -0.197785268  1.012708027 -0.0507250393  2.0947419174
411  0.804626895  0.207937102 -2.040406186 -1.1014667256  0.6016629162
412 -3.567573155 -0.533946972 -0.797119007  0.0144200085 -0.2560535349
413  3.035654687 -0.501492208 -2.162310363 -0.4796049384  0.3076485072
414 -0.275512837 -0.783122942 -1.420527155  0.8753154654 -0.8572611735
415  0.285180695  2.715375257 -0.787594761  1.1177158992  1.4098644569
416 -2.539871148 -0.212726518  0.440346818  0.3623081397 -0.4708403870
417  0.371167626  0.059360084 -0.019097338 -1.5772039870 -0.8017452349
418 -1.289012570 -1.414560663  0.348695646  1.0599176867  0.3789649575
419 -1.593501656 -1.353185598  0.795254415 -1.4227286347  0.3896108903
420  4.203137041 -1.160356824 -1.360319548  0.9402144486  0.2030264783
421  1.003380566  0.783006938  2.432824236 -0.5065157269  1.2948308220
422  3.037440694 -0.764234558 -1.671445773 -0.4052082623  0.9391522999
423  1.118865283 -1.627613105  0.820626783 -1.4740480560 -1.6234238698
424  1.192647572  1.052748980 -0.320208557  1.0166915694  0.7958130968
425  1.647246140 -1.794108562  1.088701323  0.1563622229 -0.9483002613
426 -2.217368434 -0.767971009 -1.560255532  1.0753874988  1.4168124541
427  1.998933487  0.240060907 -2.049446681  0.3665813010 -1.7574729774
428 -0.530870874  2.929224342 -1.316858555  0.5940480718 -0.8285920440
429  0.886467782 -1.534651136  0.123680123 -0.6223699015 -2.5864965539
430  1.147510416 -1.450118809 -0.462312330  0.8558115611 -0.2147881999
431  0.756466836 -0.750058355  0.462461745 -0.3822074768 -2.9719593670
432  0.361042703 -1.365185117 -2.002486280  0.0234423796  0.5694787045
433 -2.329567526  0.640045775 -0.720937687 -1.5917681774  0.1156657938
434 -1.940233708  0.577701799 -1.734470128 -0.8841403116  1.2933239252
435 -1.080274233  0.225380803 -0.416656458  0.7416002207 -0.8932138261
436 -0.759088001 -0.946019375  1.191556821  0.4659693106 -1.4255224948
437  0.129143741  2.056860056 -0.083654539  0.5835327964 -0.6823928184
438 -0.916407358 -1.456550993 -0.042815401 -0.8717082816  0.9359724829
439  3.183492916 -0.488048402 -2.016874170 -0.9989022971 -0.7332141863
440 -0.184353941 -0.305290427 -2.226196890  0.3623267078 -0.6227332985
441  2.018131030 -1.794233473  1.821714049 -1.8660714141 -0.2791139850
442 -0.899563128 -1.355011486 -1.237237674 -1.1226622294  0.8392266470
443  3.425055200 -0.932358396 -1.216255057 -1.3899565674  0.5246474597
444  0.752918896 -0.817436231 -0.197883834 -1.5675387895 -1.5142040721
445 -0.224322153 -0.413526573 -0.412144639  0.4428332084  0.3530499353
446  1.781019356  1.801531066  2.194767763 -0.1786573326  0.0384357933
447  0.417785043  0.880396872 -0.008671631 -1.2462231653  1.4003173882
448 -2.985071394  1.172534088  0.243007794  0.0303511161 -0.8185134331
449  0.728539946  2.168380865  1.611665245  1.0656956771 -0.3118559742
450 -2.226859798 -0.315948195 -1.924907297 -0.2469446457 -0.7149641667
451 -2.583308990  1.462060541  0.898523332 -0.6934271177 -0.9090347515
452 -1.111596474  0.817299019 -0.902128306  0.4005467756 -0.0734952753
453 -1.305897707  0.640291709 -0.279361998 -0.1257357962  0.9649752338
454 -1.950951666 -0.427486404 -1.760880296  0.5570824925 -0.7252212334
455 -1.465411448  0.098585736  0.139257755  0.2771735928 -0.8776894306
456  2.902098400  0.068411590  0.662370259  0.4687108845 -1.5928294679
457  1.197163818  2.653749529 -0.755502966  0.5876632138 -0.5624385746
458  3.982565596 -0.864496629 -1.051971021 -0.6484727530  0.4790902436
459  2.065760108  2.544697577  0.523636739 -1.0959766512  1.0694936969
460 -0.914678842  0.273771765 -2.228907568 -1.9490405755  0.5186990042
461 -1.104668553 -0.045821189 -0.165830790  0.2858142953 -0.8355940717
462 -1.344848644 -0.763032427  1.860801855  1.4540008318 -0.7707635519
463  0.548381658 -0.395672118 -0.886841500  0.3523488331  2.4132296694
464  1.129660602  1.150719817 -1.070362603 -0.4963616725 -1.3485840801
465  0.507712254 -0.693363136  0.350707759  0.6009791346  1.7629600093
466  1.725113043  2.457083546 -0.386850664 -1.1103403014  0.1746236276
467 -0.724707049 -0.504037231  1.435797809  0.8115334660 -0.0927063586
468  0.085667462  1.795404006  1.205727169 -0.4742829577  1.6828064772
469 -0.904670131  0.020326660  0.527192974  0.9631538199 -0.6671694468
470 -1.198712444 -0.841789928  0.328799454  0.6466320042  0.7211712753
471  1.573201936  2.938285790  2.276373053 -0.8852994950 -0.6525857934
472 -0.513739781 -0.099423820  1.633751446  0.6872523675  0.0554943306
473  1.258719150 -1.721986234  2.001006482 -0.4478864856  0.4452452088
474 -3.285205071 -0.073143324 -0.147205924  0.7296872425  0.1309057219
475 -1.738702794 -1.775506546  0.038210145  0.4500436421  0.0900086505
476  4.058607941 -0.656848814  1.730587357 -0.2354768418  0.4489631927
477  0.859892690  2.775359387 -0.605832037 -0.5457554881 -1.2841347344
478 -2.344076199  0.849140112  0.148747950  0.1663402158 -1.4176258963
479 -0.283622514 -0.829219784  0.171746374  2.0035314433 -0.2591391556
480 -0.918321369 -0.677900650 -0.895859617 -1.2658194490  0.1072217640
481  0.165873044  2.020215870 -1.569913811 -1.3312447956  1.1798092485
482  1.811705178  1.996173191  0.145391389  0.4338590366  1.8738628262
483 -0.935683564 -0.550648892 -0.633251421  1.4038972055  0.5797645170
484 -1.130505488 -1.247840403  0.769744140  0.9755623136 -0.8393725473
485  2.627847197 -0.113244398 -0.560210983  0.5439472001 -0.0536656777
486  3.269654595 -0.572200359  0.139751248  0.1712636334 -0.1611201837
487  1.031963791  1.475226353  0.403037817  1.6442510487  0.8359055754
488 -0.303447400  0.790707338 -2.448143879  0.1219832000  1.8977570357
489 -1.301374676  0.938773156  1.017404220  0.9537636486 -0.8738838970
490 -2.613492760 -0.389369182 -0.230139562 -1.8146261233 -0.2500462086
491 -0.563591531  0.006103168  0.629391510  0.8679235432  1.0009272240
492 -2.536412441 -1.523392156 -0.132274114 -0.2780986374 -1.6484326529
493  2.962050920 -0.167512799 -0.949452486  0.4636698574 -1.4297772720
494 -2.250607954 -1.255446438 -0.559550393  1.1573101714  0.0263849732
495  0.222648339  1.713051264 -0.754133612  0.5981051606  1.6281790152
496 -0.071833692  3.685377834 -1.791680567  0.6959207140 -0.9935904300
497  0.632534803  0.527653116 -0.946688552  0.9568799112  0.0164215768
498  3.190702102 -0.643622971 -1.532247193 -0.5560634181 -1.0845714660
499  0.067788727 -0.730342198 -1.692750332  0.2115209837  0.4204542957
500 -1.557925883 -1.359202344  1.073791112  0.8902098199 -0.4567071655
501 -1.284473183 -1.886379996  1.730650838  1.6352679896 -0.3012844782
502 -1.179164713 -0.468945153  1.068108756  0.3691241426  1.8727037430
503 -2.061457312 -0.415449413  0.990036774 -1.8085840650 -0.9528390644
504 -0.976620664 -0.135390388 -1.105802714 -0.4102386686 -1.1130319746
505 -2.639578247 -0.098544710 -1.866181656  0.3637025157  0.1897360313
506  0.222193084 -0.720955200 -0.496183573  0.5950160783 -0.8786423013
507 -2.111908751 -1.242557735  0.389972581  1.6957130131 -0.5726996831
508  1.896192663  0.340187303 -0.408318274  1.3169961627  0.4986774572
509 -1.581143327  0.149710189  1.012566810  0.5925528152  1.1313419266
510 -2.075771263 -0.032824254 -0.118851306 -0.9876831222 -1.1028500258
511  0.304680315 -0.548887905 -2.610593636 -0.1867373231 -0.0713777989
512  4.528372977 -1.379659835  0.224027396  0.5714119286  0.3757265507
513  1.628301041 -2.001426884  0.635973293 -0.9463866017 -0.4272720380
514  3.783471715 -0.982085240 -0.867815010 -0.5201856963 -0.2794297618
515 -0.702713566 -0.123336526  0.932961697  0.1107421298 -1.9107973896
516 -1.922830015 -0.266647180  0.920323836  0.1062557864  1.2285044939
517 -0.702553465 -0.018012444  0.918990470  1.9466279316  0.0067029959
518  1.776936706  0.613550653  1.267636252  0.3721597860  0.3381408511
519  2.832623463  0.133987309  0.238488900 -1.4684326326 -1.1824344504
520 -1.428270518  0.801207044  0.004713416 -1.5987050168 -0.2471136246
521 -0.427771395 -0.499845315  1.470718121 -1.4414350352 -0.0978732751
522  0.140101371 -0.395246817 -0.559351345  1.5356873624  1.7495196325
523 -0.881682242 -1.470592282  0.390564521  0.4968310326  1.3187625063
524 -1.717031381 -0.566446971  0.892814126 -0.3918161160 -1.7972263699
525  0.858214401  3.125505245  1.056689779 -0.5516579416 -0.7424171919
526 -2.745010696  0.132682889 -0.361240071 -1.1427445719 -0.3130019179
527 -1.171771664  2.455592754 -1.182960521 -1.1628137316  1.1278306171
528 -1.057379010 -0.107416898  0.246049138 -0.3503030866 -2.0843650302
529  1.186482127  1.243421842  0.880878112 -0.1267683479  1.3151066690
530  3.398247477 -0.493326931 -0.990692540  0.8886435808  0.6146366063
531  3.262043594 -0.270249747 -0.408992843 -0.3640557052 -0.6074158633
532 -1.346150802 -1.513665065  0.167317873  1.3737510786  0.2227268141
533 -3.255135479  0.695710350  0.237308568 -0.1440530885 -0.3975828571
534 -1.058840714 -0.106772617  0.328890352 -0.3965286476  0.6413304825
535  0.033165348  1.336629330  0.270238847  0.9653475904 -1.4155030320
536 -1.576714630  1.464902809 -2.447705390  0.9703636200 -0.7517274445
537  3.452332127 -0.214833817  0.604353392  1.2416798075 -1.3404592431
538 -1.674213891 -1.735019372 -1.091198185 -1.4175330302 -0.2101656621
539  3.507730669 -0.878034184 -0.413067740  0.7242803809 -0.5362100369
540  0.263296489 -0.135176939  3.064574348 -0.4259722166  1.1851937476
541 -0.960666456 -0.037073694  1.168810852  0.4293641702 -1.5259547368
542  0.881039592  0.489967477 -2.202944449  0.1606689803  0.2178463187
543  3.770162983 -1.103403659 -1.285198679  1.3353383319  0.8431719227
544 -2.314817388 -0.097306395  0.741982273 -1.4229237773 -0.1626328351
545 -0.993013310 -0.124002071 -0.508825850 -0.1109836562  0.4778189626
546 -1.023180507 -1.122487581  0.944721304 -1.7885992520 -1.1307868089
547  0.629052819 -0.131524021 -0.081511787 -0.2109219994  1.3572833460
548  1.532692641  1.676172315 -0.865353702 -1.5498826506 -0.1605925193
549 -1.216501387 -0.006143500  1.796461942 -1.0730866350 -0.8754285023
550  0.410509831 -0.785827258 -1.456290716  1.1933515397 -0.3756609259
551 -1.121746202 -0.561229355  1.301404549 -1.6912584383 -0.5421121641
552  2.095704657  2.051589361 -1.026697264 -0.6162492541  0.5287961407
553 -1.751447499  0.419382734  0.629755124  1.1022236498 -1.4120285676
554 -2.172571315  0.515614836 -0.175409467  0.2721559757 -1.7965817906
555  0.619108371  1.692357445  0.502748598  0.2738396792  2.3867882516
556 -0.023427311 -0.300716914  0.780115748  0.5728741735 -0.1192716005
557 -0.938468873  0.481614045 -2.682276488 -0.9431910830  1.3357497558
558  3.601662993 -0.691914411 -1.276379668 -1.7560363273 -0.0027625388
559 -0.342999283 -0.723813152 -0.237179091  0.5943927631 -0.3944408313
560 -1.338028913  0.500897630  0.274784549  1.4016131277 -0.0896771836
561 -0.923169472  0.527494400  0.194524244  1.7317331298  0.1268337468
562  1.474393793  1.015370626 -1.036366955 -0.6929815012 -0.2875437386
563  0.514501885  2.980358155 -0.291957425 -1.8418750345 -0.1292969576
564 -0.088381525 -0.986433440  2.197311593 -0.8333956217  1.2623607385
565 -0.308443652  1.692746756 -1.919312680  0.3142333017  0.5609579694
566 -1.273371929  1.215910992 -1.220342892 -0.6663749333 -0.4476019966
567 -0.810328680 -1.493617916  1.544164448 -0.0893077459  1.4636022548
568  0.157021373 -0.398061987 -1.231170075 -0.0494827660 -0.4807511195
569 -1.226925889  0.154811153  1.582875424 -0.8308299622  1.3628083585
570 -1.542370457  1.159452858 -1.643190658  0.3636494950 -1.8170713038
571 -0.964100337 -0.729406783  2.002079563 -0.5086405518  1.4246983234
572  2.177531820  2.087068835 -0.609043882  0.5939488392 -0.4268983871
573  4.124623002 -0.910668659  1.052518896  0.3092132176  0.1822854216
574 -1.136927301 -0.406594160  1.333741741  0.7706340510 -1.2260979677
575  1.793947497  2.911293713 -0.579698895 -0.3218368920 -0.8851693889
576 -1.922027400 -1.131986079  1.089118026 -0.9672065075  0.3932615948
577 -0.253146222 -0.531864470 -1.294905755  1.3800447823  1.3067562905
578 -2.096490499 -1.470742235  0.304233538 -0.2286906106  0.4389066943
579 -1.541659532 -1.191284882 -0.288908773  1.2191590924 -0.5052185390
580 -0.487773107 -0.277022644  0.856110436 -0.4683622206  1.9558526259
581 -1.887219804  0.832261512  0.741135014 -1.4023755687 -0.6667935690
582 -0.809033130 -0.865069235 -1.663799146  1.1081840695  0.8806128555
583 -0.329427434 -0.062442815 -0.226413004 -0.8368039240 -0.3676105676
584 -0.479948278 -2.423232310  0.898227305  1.3280484238  0.4293939545
585  1.337011276 -1.990715231 -0.336905484 -0.5796545534  0.8399482580
586 -1.653654741 -1.084411544 -0.691897624  0.3988227450 -1.7389228243
587 -1.730942848 -0.164770550 -2.344669385  2.1380197417  0.5883620496
588  3.784335911 -1.156718106 -1.043352578 -0.9852024662  1.5383577691
589  1.057529974  3.095745110  1.180874581 -0.6976563054  1.3460053406
590  1.948890141  2.022084557 -0.504716499  0.4036165118  2.1305578518
591 -0.964375689  0.082302590  0.019592186  0.5677428537  0.1138136158
592  1.093489550 -1.661223744 -0.282141302 -0.4521015068 -1.2852354202
593 -1.002432800 -2.012118574  0.891964202  1.0377463517 -0.5588645523
594  0.580309812  4.241548842  0.763472811  1.6204500909 -0.3685912542
595  0.579497768  2.600650139 -1.460019281 -1.0455250963  1.0260170015
596  2.951560187 -0.182819149 -2.297099305  0.0502733137 -0.9151324842
597 -1.436644212 -1.123848694  1.046036718 -0.1006624780 -0.3509053972
598 -1.982806411 -0.817948568  1.646996982 -0.0852096248  0.4922871431
599 -0.335095174 -1.608041744 -0.470936003  1.0757829213  1.2210097841
600 -0.655729466 -0.677709108  1.164225860 -1.1015947305  0.2788630337
601 -0.578547040 -0.106854067 -0.961429830  1.2239934966  0.0105352964
602  2.784580159 -0.103011459  0.181395704 -0.2524837896 -2.8172625153
603 -0.600090752 -0.149714978  0.040343568  0.3634235234 -1.1464531044
604  0.534519480  3.295825639  0.976098216 -0.2267991495 -0.4644950407
605 -2.887795572  1.373182346 -0.251281156 -0.5623663281 -0.1732884401
606  3.129572449 -0.483199590 -0.899073478 -0.6214053558 -0.3377521056
607 -1.080404107  0.336114925  0.645947431  1.8225761772 -0.2402320714
608 -1.751327249  0.501620492 -1.080784247  0.4032183197  1.5237196726
609  1.893121972 -1.853070064  1.102230222  0.0631448627  0.3891410049
610  3.583460665 -0.610206346  0.205028971  0.9778285669 -0.4458579045
611  3.368589146 -0.867213274 -0.421180340 -1.1439542485  1.0416527627
612  1.407354420 -1.490874875 -0.422909614 -1.5721588338  0.4540366657
613 -1.236055435 -0.823527454 -0.377206303 -0.9806526387 -0.4194346161
614  0.988330660 -1.368972496 -1.470234217  1.0751375908  1.7472394430
615  1.833812632  2.940307328  0.377234391  0.0800810124  1.5188371422
616  3.297564456 -0.409692529 -1.062733794 -0.8818040526  0.1569943303
617 -1.311600768  0.023387220  0.816923818 -1.9641431917 -1.1598765531
618  0.471162784  0.032662274 -0.284448628  1.3061735962  0.6592687728
619  0.660250902  1.155090888  1.051335109 -0.6700267980  0.2199125664
620 -3.257207923  2.059332122  0.854321407 -1.9060223157 -0.5014835270
621 -0.161843444  0.943496259 -1.212879125  0.7700708048 -0.6048934127
622  2.539892478  0.253180200 -1.612708117 -1.4275939409 -0.5930599896
623  3.497287531 -0.709679311  0.515970859 -0.3286350891 -1.3489459601
624 -2.578213827  0.978755995 -0.726998191 -0.0197739393 -0.6440544065
625 -1.728167227 -0.796439423 -0.898645317 -0.7677602250  0.7898186230
626 -1.671389460 -0.501685807  0.100920557  1.1353796022  0.6062441269
627 -0.850626190  0.311898656  1.581970600  1.0915661986 -0.8165140817
628  1.473791283 -2.212922160  0.137330382  1.0549214133  0.4283625316
629 -0.907216056 -0.804822239  0.954862307  0.0626264428  1.8958089899
630 -0.849753611  0.116566394  0.177717214  0.7716495071  0.3099918640
631  3.271075973 -0.251304537 -0.267813581  0.7455388605 -0.2069810449
632  1.322111046  0.282907663  0.277867161  1.6297640570 -0.0168981616
633 -1.746784015 -1.411022663 -0.657018118  0.5084516809 -1.6361992299
634 -0.183917649 -0.562448204 -1.818834896  0.8471471676 -0.0308424706
635  0.379433773  1.522447306 -1.285599454 -0.5318099747 -1.0028262636
636 -1.895505448 -0.521898250  0.786088529 -0.9183698831 -0.7166979381
637 -1.014999757 -1.013733690 -1.730187008 -1.6505970123 -0.1847837777
638 -0.431089883 -0.959248007 -2.134588151  0.0888189582 -0.9829645145
639  3.083779837 -0.064609814 -1.846231717 -0.3582435208 -0.1313528691
640  1.110429990  1.367603940  1.111560494 -1.0998061059 -0.2693856359
641  0.856606980  2.081814709  0.007533039  1.5727317337  1.6221319321
642 -0.936536461 -1.812380299 -0.253950652  0.5329189003 -0.1153321862
643 -1.966882081 -1.036773131 -0.149262824 -0.1992393859  1.2152960593
644 -1.903143684  1.978514299  1.265244594  0.7443027577 -1.2010292897
645  1.223812982  3.237023672 -0.027635617  0.3034859895  2.1546378550
646  0.455509666  0.027609443  1.443631686  0.5137513332  0.7862614746
647  4.324852409 -0.829498890  1.951553857 -0.5996782994  0.5541120680
648 -1.710415062  1.831313000 -0.614457823  0.1412173665 -0.6087631082
649  2.580792969  2.033889678  0.561068564 -0.1244176427  2.5964608292
650  4.067444752 -0.921508476 -1.130635019 -0.2812938683  1.2534139924
651 -3.192746312 -0.085130092 -1.212645791  0.2404837035 -0.8728026227
652 -1.098574624 -1.862966571  0.403185077 -1.6184563840 -0.0350516656
653 -1.070390707 -0.158255537 -1.143554200  0.2382478005 -0.7593913465
654 -1.500465456 -1.337415755  1.436475514 -1.3420872170  0.7970035088
655  0.885108094 -1.199443095  0.306950973  0.5233947663  0.6612111131
656 -0.572959407  0.133735304  0.628883348  0.9086946124  0.0592950365
657 -1.227867427  0.453074484  1.649105372 -0.3848683001  0.9454115545
658  0.421016495 -0.583685039 -1.273549553  0.4661977034  1.1319783396
659 -2.373015390  0.013405026 -0.271821578  0.0390003660 -0.6797660686
660 -0.178217388 -0.406591783  0.595405130  1.1830107379  0.6470477624
661 -1.845417563 -0.752784826 -0.225702505 -0.6336048708 -0.7879771213
662  0.863112390  1.847118314  1.082293976 -0.5124945022 -1.5458488984
663  0.148914039 -0.069770314 -2.626978049 -0.8666897809  0.3499328953
664  1.180110745 -1.937865233  0.508851102  0.2613342470 -1.5469250545
665 -2.734579173  1.646290019  0.755176426  0.2682689840 -1.2977839205
666 -0.577260782 -1.131433936 -0.748026179  2.5359618089  0.6843948020
667 -1.891494813 -1.357187467 -0.061692910 -0.1892567151 -1.4754990663
668 -1.887938987  0.770537531  1.217455418 -2.3066301484 -0.2929414253
669  3.592554054 -0.640771018 -0.271577673  0.1110188958 -0.1030025591
670  3.102242256 -0.691063390 -0.661604443 -0.6887763569  0.9529394179
671 -1.106099656 -1.369187970 -0.052679489 -0.0179654365 -0.7691937006
672  0.004516314 -1.416788830 -1.267424226 -0.8147816239 -0.2331718855
673  1.142015841 -0.705729789 -1.479429532 -1.1011608249  1.1603453929
674  2.766383288 -0.532585275 -0.006652686  1.5799693091  0.2619063069
675 -2.513151005 -0.309486849 -0.284356593 -1.7088462948  0.5312091629
676 -1.579416103 -0.075570921 -0.690164101  0.0936465598 -1.6322688344
677  1.064221113  2.077630227 -0.600971621 -0.3599995993  2.2723823240
678 -2.219668777 -0.907178295 -0.221354383 -1.0194259886 -0.9916273606
679  0.670656817  2.664272247 -2.054706909  0.3817542280 -0.7370266212
680 -0.526746818  0.077574582  1.454337984  1.3091029814 -0.4366539842
681  0.786796712 -1.204746906 -0.663846987 -0.6339241283  0.8346564843
682  0.581315920  1.784775228  0.140172532 -1.7190152351 -0.1633931232
683 -2.188297458 -0.011778507 -0.922027550 -0.6800295179 -0.0445216795
684 -0.347348525  0.029419983 -1.297887103 -0.2051673251  1.0730123639
685 -1.478860742 -0.893267665  0.723757323 -0.2546667307 -0.2268556508
686 -1.423270443 -0.730494692 -0.438503516 -1.0636535086 -0.0043556625
687 -0.423706587 -0.632608794 -0.836113284 -1.3514487412 -0.2101731133
688  2.247170184  2.164783289  2.835239515 -1.2816798457  0.9114033012
689 -0.707387227 -0.385318844  0.440661601  0.2836679200  1.2129923949
690  0.850519650  0.355123278 -0.802519350 -1.7090427518  0.5251752940
691 -0.009206745 -0.805257116 -0.499015794 -1.0016535075  1.6338077867
692 -0.159477148  0.404520786 -1.353154231  1.2375201091 -0.4775458963
693  3.055302731 -0.687615011 -1.241877136 -0.2330458967 -1.6969715766
694 -0.142146194 -0.920469344  0.209937366  1.8806880777  0.5411050221
695  0.376144528 -1.138112960  0.135213883 -0.8379813745 -2.3213529597
696 -1.279960533  0.310019854  1.327318626  0.6675416278 -0.4510836783
697  0.719423573  2.771652547 -1.303893753 -1.6479549927  0.5651346742
698  0.179652653  0.909883115  1.542348754  1.2054541235 -0.6818704359
699  0.655010388 -0.314605599 -0.877071962  1.1464262551  1.1906773369
700 -1.886380591 -0.494226109  0.596121664  0.2560436692 -1.4751992840
701 -0.039656264  0.915102979 -1.078897684 -1.6065031561  1.1467125441
702 -0.922877691  0.561088199  0.714908844 -1.7891886182 -1.1911446858
703 -1.673144726  0.352289991  0.774767246 -2.1194747026 -0.0490065435
704 -0.411773463 -2.120710981  0.320962235 -0.0620439017  2.1999517522
705  0.995163509 -1.103531060  0.526907218  1.5739312731  0.6036436302
706 -2.640809011 -0.839853413 -1.855714351  0.2630792285 -0.4517272030
707  1.579860734  2.329451889 -0.736843277 -0.5229865818  0.0525799919
708 -2.223765945  0.402003865  2.010064701  0.7454667589  0.6157824838
709  0.170806883  0.202081973  0.277525007 -1.2844562242 -0.3865518673
710 -1.956592655 -1.569944238 -0.467680482  0.2312922788 -1.4632501186
711  2.045187543  2.316678137  3.224135798  0.5052150031  0.3641138129
712  1.248503819 -1.620225054  0.438288211 -1.6571263600 -1.5865794831
713  4.689058005 -1.799500642 -0.441792618 -0.1614961114  2.2793273683
714  0.112167693  0.279381636  0.162048863 -0.9501498588  0.6000927831
715  1.920141303  1.850148775  1.720009734  1.9104341748 -0.3586001854
716 -0.246111750  1.095982036 -0.083603459  1.7348232443  0.1003370917
717 -1.645622665  0.241179965 -1.419471122  0.4190139745 -0.6275967429
718 -2.539244814  1.079100902  0.680919176  1.8538983752  0.0252733610
719  1.109151151  2.314376203  1.543250108  0.3480600870 -1.2097476213
720  0.914137164 -1.804577566  0.805569690 -0.7085640017 -0.8876031385
721  0.699695548  0.140363510 -1.132979576  0.5786014461 -0.3468150866
722  1.583594762  0.971686208 -1.468845158 -0.4683941811  0.7240924700
723 -1.074437013 -0.985908834  1.198317704  1.3286915155  0.9198854206
724 -0.833884764 -1.123994934 -0.467808606  0.1448498446 -1.5550363124
725  1.677737173  0.623513179 -0.054841315  1.4762571361 -0.3819784127
726 -2.216599474  1.089901752  1.273744819  0.6971429741 -0.7147167753
727 -0.654245946 -1.653689531 -0.888042433  0.4553754767  0.4271033759
728 -1.564246915  1.287156204 -0.955056315 -0.8137111643 -0.5431254783
729  3.979154647 -0.920963871  1.717856569  1.1218173626 -0.3921617302
730 -1.263646503  2.790150448 -0.058172793  1.7772821745 -0.4965869061
731 -2.008752938 -1.433253776  0.837867918  0.3679333925  0.9916209333
732 -0.505011584 -0.037366927  0.636748035 -2.1500285115 -0.5315791979
733  0.475797981 -0.754012466  0.443275451 -0.6136650928 -2.2290880828
734  0.297898900  2.630590002  1.019296814 -1.6248488034  0.2433746514
735  1.428240289  1.583764789 -0.744721814 -1.5085433760 -0.1626283187
736  1.447144438 -1.539340759  0.911078906 -0.5074487248 -0.3964800989
737  3.555369255 -1.000166009  1.796550046 -0.0367716774  0.6421542516
738  1.660851111  1.292904776  1.615398405  0.5588299434  1.5420507075
739  4.020683706 -0.741600279  1.018479434  0.2821418220 -0.0668312474
740 -0.070052309  0.917359484 -0.070780344 -0.0963813922 -0.9126085085
741 -0.593899883  0.125677764  0.811109439 -1.4178057898  0.6395087736
742 -1.454264706  0.728316407  1.863608167  1.6949434318  0.2778413664
743 -3.340963978  1.009959641 -0.638100159 -1.6322333463  0.3767693986
744  0.635053228 -0.164865227 -1.579002776 -0.7571248606  1.9055060637
745  0.041762505  0.121478931 -0.333021768 -1.1415855690 -0.0370086189
746 -0.398986443 -0.501720868  1.394523540 -1.3349995009 -0.3538887247
747 -0.048099850 -0.470429272 -1.713538856  0.5588307357  1.2257877346
748  0.649817579 -2.102197359 -1.727008769 -0.1781446068  0.7885302915
749 -1.731278644  0.649985239 -0.028554429  1.3971940991  0.4135697088
750 -0.614322883  0.064823680  1.762646063 -1.6380325369 -0.5327077486
751 -2.187147289 -0.242694235  0.437415363 -1.1805582817 -0.9105667118
752 -0.532974804 -1.142556883  1.046892522 -1.0015343020  0.2764816951
753  0.169589411 -0.355341957 -1.072683785 -1.0766041860  1.5725289635
754  0.667712387 -0.794695723  0.740290644  0.9301905968 -1.7753523290
755 -3.142287207  0.289842999 -1.175731179 -1.0757627347  1.3559613976
756 -2.487684144 -0.125434884 -0.472573175  0.6606492833  0.2171649448
757 -1.880090820 -0.912684877 -0.476602890 -0.9960251353  1.1196046745
758 -0.385738710 -0.412884907 -2.402120656  1.8439224979  1.3227136857
759 -0.677480928  1.158316033 -0.173187544 -0.2273138410  2.1725358660
760  2.537857843 -0.239488361 -0.411664605  0.8383939006 -0.0140964788
761 -1.923097794  0.019843216 -0.050266664  0.4257319191 -0.0155921730
762 -1.957653068  0.235518314  1.011021108  1.5860230020  0.7260334565
763  2.558324194  2.033504363 -0.798649524 -0.5679075011  0.0102667789
764 -0.853717893  0.083821281  1.713252206 -0.2886024678 -0.5977458855
765 -1.687157593 -1.923919054  0.166378401 -2.1887050700 -0.5625024386
766 -0.283566183  2.589438946 -0.689018876 -1.0531599654 -0.7011714784
767  0.922821260 -0.135235942 -1.697327902  0.1696698441 -0.0717889971
768 -1.151793468  0.019496741 -0.197453447  0.5154585980 -1.3281290086
769 -1.799005119  0.948235295 -1.580371375  0.4872744831  0.9758358435
770  0.894116693 -1.435757696  0.498178590 -0.8114457347 -1.4358202307
771 -3.196448597 -0.731732771  0.699275790 -0.5369276991  1.3951469107
772 -0.750757892 -1.247092232  0.351500288 -0.5638298022  2.1383659414
773 -1.174064393 -2.068581215 -0.271100773 -1.6612321633  0.4402033336
774 -1.123597125  1.534013118  0.458503582  1.5086732533 -0.4251725669
775  3.205715350 -0.500547302  0.255856545 -0.9201511972 -0.3003645049
776  0.789757486  1.597817475 -0.196797980  0.7393101056  0.1909184002
777 -0.319728319 -0.963981805  0.272968072  1.0907341274 -0.4481910901
778  1.364331859 -1.560236235 -0.942927978 -1.3149129762 -0.6725540216
779 -1.600847317 -0.796366416 -0.141865168  1.0702608231  0.8244976392
780  3.573570810 -0.740887134 -1.081805894  1.4393435384  1.0736649588
781 -1.431260659  0.111104838  0.504412642 -1.9115136022 -0.3234573550
782 -0.791259543 -1.084843526  0.618494449  0.7227302767  0.7929953927
783 -2.383868314 -0.309960030  0.658347405  0.3348137725  0.3502181871
784 -0.936606255 -1.932069351 -1.257585636  1.3436893173  1.2807424078
785  3.679597528 -0.538228578  1.278420924 -0.4356210764 -0.5536945549
786  1.517559053  0.910506245 -0.021111245  0.8886602914  0.3935771139
787 -0.872738596 -2.019247484 -0.584384844  1.6364607487  0.4272011611
788 -2.471944773  0.800668596 -0.419002538 -2.2180027102 -0.0367391055
789  1.662252022  0.018142564  0.316522970 -0.1860346201  1.9545082992
790 -1.246113331 -0.703739590 -2.520623354  0.5234056735 -0.6914409448
791  2.799929832  0.030962912  0.260971332 -1.5251937361 -1.5813066995
792 -0.189712833 -1.344279566 -0.373622889  0.5240406384  1.0418893618
793 -1.343174478  0.794780722 -2.671164738 -0.6995988099  0.8240681712
794 -1.951792016  0.593157923 -0.094526856  1.4150999243  1.5000956732
795 -2.383315399 -0.050786340 -1.994199198  0.1199754811 -0.3530958417
796 -0.831108284  1.239145212 -0.530761262 -0.2342804338 -0.3136769961
797 -1.409094450 -0.117256861 -0.695302839  0.3487014242  0.7484835120
798  1.288269568 -1.600539276  0.241030305 -0.6848137219 -1.4352941223
799  0.172217324 -2.096761581  0.555933903 -0.4282159827  1.7629083322
800 -0.934285317 -0.082772879 -1.206876674  0.0940239720 -0.0223586724
801 -0.562909011  1.384327660 -2.729073642 -0.3499597127  0.7533781384
802  3.823239487 -0.697557062  0.223833900 -0.5922823495  0.7773423893
803  0.490671805  0.271103805 -0.902849256 -2.0531891607 -0.1317156848
804 -2.122884215  0.920651229  0.537165687 -0.5622924765 -0.8016087490
805  1.548611507 -1.044973095  0.480378079  0.4788677446  0.4250874824
806 -0.332693386  0.956649618 -0.972370768  0.1375773308 -1.5667538716
807 -1.151418324  3.912161544  0.887449564  1.1077758653 -0.3689934800
808  0.980129878 -0.060074037 -1.533269965 -0.4781047352  0.6705210913
809 -1.038371493  0.292394782  0.750886467 -0.1430460715 -0.6712113052
810 -1.873727871 -0.639528549  1.289683525  1.8240922066  0.1818817907
811  1.031181653 -0.935143985  0.750977139 -0.3801636421 -1.9235174432
812  3.379848092 -0.378766051 -0.516139227 -0.3137363285  0.9600253232
813  0.977129389  0.433943832  2.172019760  1.8604589301 -0.2723540905
814 -1.261151025 -0.562528708  0.634452706 -0.0498059153  0.4284351522
815  0.163575653 -0.627105470 -1.649378838  2.0527500997  0.3231485102
816  1.688313037  2.550958372  1.201839351  0.7811210194  1.1298974562
817 -0.411696976 -0.041891523  1.295385890 -0.2396708475 -1.2645850802
818 -1.803473633 -0.527031286  1.171299626  0.2706102539 -0.3772431762
819 -0.772521506 -0.889752788 -0.038974538 -0.3421542667  0.6070755724
820  1.250906314 -1.485051603  1.398286388 -1.1545385068 -0.9128086184
821  0.182047097  0.358509130 -1.375966011 -0.6278012946 -0.3214425940
822  0.520928689  0.367619631 -1.594596741  0.6487423799  0.7256080563
823 -1.737283541  0.275541162  0.509302943 -1.9214678631  0.2884521084
824 -1.122952408  0.513023527  0.644335143 -0.4631254821  1.0534769511
825 -2.213928800 -0.918172617 -0.521801035 -2.0460512923 -0.1095321646
826 -2.273872294  0.495578867 -1.683338997  0.5376087418 -1.7022726210
827  0.778450280  1.821584028  1.852174561  0.5448659209  0.7418689998
828 -1.891104704 -0.596018677  0.761441571  0.6203835145 -1.2060699819
829  0.649071895 -0.808572751 -2.381793241  0.0514921477  0.3567195413
830  0.590379266 -1.759641100 -0.999539524  1.4281526222  0.0693592332
831  3.648442789 -1.140602286 -1.409158817 -1.1733512574  0.4730108642
832  2.764703338 -0.010840241 -0.144748427  0.5383939981 -2.1666527491
833  0.852620242 -1.339016152 -0.646400661 -0.9524584332 -0.9107770439
834  1.072549549  3.220481160  1.679964161  1.4007726609 -0.9313065532
835 -0.866875117  0.616716004 -0.837785621  1.1796411548 -0.7999694852
836  1.009441887 -1.091481094 -0.451726369  0.2517133549 -1.8643510858
837 -0.280708182 -0.776733473  1.316927952 -0.5835839131  1.1149795303
838 -1.602661861  0.544854321  0.401022587  0.6673333910  0.2508654548
839  1.150899765  2.004985194 -0.630322479  0.2829884975 -1.3122405415
840  1.452436266  1.720759306 -1.056390821 -0.9981741863  1.0855847959
841  1.593062369 -2.129285544 -0.331610437  1.2670099619 -0.6118717148
842 -0.548132511 -0.929912304  0.131060075  1.6710310311  0.6543534998
843  0.739049815 -0.083704488  0.804531553  0.9415795956  1.1639743327
844 -2.271757836  1.619817226  0.580725586 -0.6054824940 -0.7082112345
845  0.721744662  3.125356418 -0.264954802 -1.5391740882  0.1928560978
846  1.140272267 -1.480251250  0.385978996 -2.1738363129 -1.0825421904
847  0.524781574  1.742567771  0.063790631 -0.8320039429  1.0060146123
848 -1.873831695 -1.589863339  0.497268637  1.3148487193  0.2486775456
849  2.515538857 -2.998503963  0.158828367 -0.2113161090  1.0303993962
850  0.307186284  3.945154122  0.699793205  1.2304699927  0.3270115290
851 -0.342178627 -0.623310356  1.696247415  1.3117373902  0.1717018119
852 -0.593758092 -0.546519750  0.081986338  0.3488629913  0.3006649845
853  1.974497817  2.676960794  1.492379089  0.0024015430  1.4401514866
854 -1.016863267 -0.239324205  2.231822090 -0.4354341387  1.6233233541
855  1.634155105  3.597851113  2.745946619  1.3850718314 -0.1043868011
856 -0.322462125  1.331083390 -0.390735833  1.3392106753 -0.1563977555
857 -2.620346221  0.822577065  0.928306008  0.6806851279 -1.2576521172
858  1.027191891 -1.142348263  0.986269309  0.3768792379 -1.9005455142
859 -1.541807245  0.447388849  0.095086645 -0.8021383394 -1.4862141359
860 -3.371860824  0.031041582 -0.618340553  0.1130837925 -0.7299306368
861 -1.607815299 -0.932582950  1.223716525 -1.7136171611 -0.0763049792
862 -2.174503145 -1.565004826  0.392594710 -2.0620535021  0.3146216073
863 -2.303032096  0.456627810 -0.591788807 -0.9359711660 -0.2524730953
864  2.643591849 -0.281359700 -0.850548152 -0.2120417143 -1.4280499269
865  1.470879919 -1.981920241  1.146510906 -1.7728021866 -1.4771787065
866  1.352157192  1.452988166 -0.583993072 -1.4981862135  0.5809893876
867  1.715489345 -2.206339427  1.525736648  0.2876007163  0.5050142550
868 -2.185452208 -1.174554981 -1.110056760 -0.7539975895  1.2207963949
869  0.539911510  4.381701837  1.577044166  1.1750734818 -0.0922525986
870 -1.300277220 -1.613616500 -0.182291553  1.7925597444  0.4024894806
871  1.626145165 -1.584354625  0.628397632 -2.0459071018 -0.3544236036
872 -0.882736537 -1.490699589  0.623549492  0.1773611945  0.8978184988
873 -2.743196444  0.500575682  0.533454457 -0.4806788571  0.7920147184
874 -2.152158251 -1.281868337 -0.602286387 -0.9901766753  0.6198006673
875 -1.304195650 -2.184063833 -0.552797096  0.2399030154  0.0675187603
876 -0.022759977  0.772001499 -0.200950507 -1.1655235218  0.1150022318
877  1.666509378 -1.894329153  1.370345754 -0.1814621504  1.1925238690
878  1.242250944 -1.371651303  0.158686490 -0.4854779919 -1.3896473256
879 -2.168178175 -0.735702900 -0.514660071 -1.5221565198  0.7083749755
880  1.194964775 -1.860913511 -0.407801561 -0.1016627362  0.1906764506
881  0.610041218 -0.078482717 -1.079416627 -1.0436045825 -0.7167435115
882  2.718193708 -0.494087161 -0.826452049 -0.0068510473 -1.6983774316
883 -0.811554479  0.389515399 -0.314141626 -0.1564615818  0.1381010032
884 -0.872060663 -1.276039807  0.181551292 -1.2047409945 -0.5175604452
885  0.515898325  2.379093588 -1.234423621 -1.7693250103  1.1557011671
886  2.727665194 -0.426624514 -0.419304964  0.6113805188 -0.2028485192
887 -1.491082901 -1.103932927 -0.621194956 -0.9487744275  0.2396103370
888 -1.190330485 -0.419448997 -0.579421367  2.2577838376  0.2928141070
889 -2.163413762  1.138431626  0.901855847  0.6892331393 -1.4309780828
890  1.206649884  0.879182461 -0.721437694 -0.9275195459  0.1371471770
891 -0.458136661  0.298724174 -0.408706769  1.3497632289 -0.0894544754
892  0.378465095  0.516947536  1.731321289 -0.4050270955  0.6181031497
893  3.416540456 -0.541940612 -1.374260754 -1.4656604698  0.5794830103
894 -1.981949963  1.300302681  0.546137760  0.7473636224 -0.9021963857
895  0.004770412 -0.688459063 -0.488775593 -0.5855921352  1.0466729707
896 -1.662758298  1.194601884 -0.823354122 -1.0532240585  0.4248942875
897  2.226861019 -2.174622046  2.367875648 -0.5136687602  0.7009496955
898  3.352805041 -0.992647252  0.391914795  1.0182263700  0.6359480362
899  1.068093635  2.070769242  0.790826207 -1.0998308939 -0.0478800587
900 -0.736193409 -0.523729732  0.899792305 -2.4979980377 -0.5928870783
901 -0.209717665  3.337649279 -1.300351049 -0.5620944524  1.0289575834
902 -1.613763433 -0.623534491  0.289547687  1.4793681938 -0.8438843191
903  1.552947258 -1.954151456  1.616937432 -0.7468737139  0.9380452424
904 -0.630476427 -0.492271385 -0.442427906 -0.8822031277 -0.5237110328
905 -1.983527608  0.264952687 -0.626423073 -2.2038496923  0.3744548961
906  0.318195176  0.262450080  0.211195543  0.2897149827 -1.6900271739
907  1.586787701 -1.784148201  0.928259940 -1.3145874886 -0.3723665689
908  0.153993265  2.425380306  0.184414756 -0.5598560942 -0.1799063348
909 -1.868530083 -0.265568907 -2.851400105 -0.8246435826  1.4140429410
910  0.115771047 -0.920328837 -2.399330804 -0.7172780698  1.1735661914
911  4.794597437 -1.402336419 -0.095639862  0.5614796050  1.4644018837
912 -0.119968815  2.260533040 -0.292207541  1.2165618749  1.2403751959
913  0.011020554  3.247559287  1.333639873  2.1081213694  0.3589491101
914  0.776961447  0.631330397 -0.915489950  1.3862493959  0.0932039532
915 -0.780159861  1.590816247 -1.060695932  1.1097849668  0.1874094447
916 -0.810739829  0.584443284 -1.477134399  0.2682524547 -0.4975132355
917  0.817020060  2.688027082  1.544041688 -1.6047553030  0.1566802298
918 -0.683498650  0.112765763  0.525281015 -0.9110457841  0.1121665125
919 -1.334940634  0.243427255  0.853671301 -0.5616830162  0.8323133752
920 -1.196594373  0.566040655  1.796262626 -1.0152711258  0.0069652080
921  2.408603187  0.629727626  0.321923755  0.1434554153 -2.1103779252
922 -0.209344434 -0.365581114  0.190404329 -0.4470278409  1.0523133753
923  1.156199204 -1.652017045  0.904551606  0.9123071511 -1.2449447728
924 -1.851228986  0.334372134  1.660953662  1.6113677588  0.1714219822
925  0.321258374  3.429495505  1.590183214 -1.8159725320  0.1995309045
926 -0.478756226 -0.431655885 -3.287390130  0.7894743310 -0.7450976376
927 -0.152547456  1.974914078 -1.379466189 -0.1694789909  0.3816191695
928  1.208488820 -0.392442143 -1.032372734  1.4148696939  0.8094751784
929 -1.710836341 -0.321296228  0.946447143  0.0478962880  1.8705212494
930 -2.189625980  0.775477375  0.230162079  0.0479852198  1.3181273746
931  1.925706597 -2.359225111  1.568342398  1.7665768964 -0.8509461998
932 -1.262762888  0.108974652  1.700006411  1.6434733603 -0.1489158931
933  2.843865752  0.002500165  0.120523744 -1.2264550012 -0.9746599133
934 -0.127005520  2.129787428 -1.374829630  1.0355341887  0.4568374729
935 -0.082940760 -0.768712319  0.620607475  0.9579168612 -0.7871118930
936 -1.891950119 -1.094214155 -0.555178315  0.0839154618  0.2453800863
937  0.329606189  3.122962299  1.863777327  0.7295223645 -1.2743573683
938  1.066668300  1.472990704  1.104238426 -1.4834669557  0.4469797084
939 -2.666089984  0.296086436 -1.409696238 -0.9136521310 -0.1909875064
940 -2.805224030  0.286426265 -0.530189372 -0.3951982101  0.4160472314
941 -1.184350348 -1.466406227 -0.237323725  0.0008854083 -0.6674278392
942  0.155933633 -0.866822030  1.382732169 -0.9807358055  0.8193115572
943  2.872939527 -0.056102240 -0.803966029 -0.6003818522 -1.4811945463
944  3.382472224 -0.600034211  0.627349113  1.0393182538 -1.8369798304
945  1.419320630 -0.738467580 -0.856460123  1.3107608266  1.1703102700
946  1.254739955  4.113957963  1.376126473 -0.9745460308 -1.1687557220
947 -1.665017060  0.494275892  0.840773253  1.4836542694 -0.3335108597
948 -0.981327251 -0.521262367  0.489805015 -1.0096481248  0.4925066424
949  1.056410537 -1.701669902  0.393182392 -0.1212371899 -2.9377648146
950  0.728203294  1.357827612  0.112494490  1.1571878605 -0.9690033236
951 -0.410633677  0.277446080  0.793577510 -1.3834292852 -0.7320159344
952  0.183229426 -0.446565701 -2.600576851  0.6291902406 -0.4191061520
953  0.141418914 -0.701983619 -0.084040389  2.0299426096  0.5537760626
954 -1.331547017 -0.007601604 -0.031572565  1.7202301653  0.8750094941
955  3.906141191 -0.774980767 -0.954287712 -0.4137845594 -0.7280039572
956  0.453454189  1.652318179 -1.743465677 -1.2095555662  0.1842049895
957 -1.726447063 -0.974936561  1.132572332  0.4119824072 -1.1750807056
958  0.842207080 -1.454370258  0.192306653 -1.0277797735 -2.1496570404
959 -1.605211485  0.290093838  0.204377330  0.3748475064  1.0110009364
960  0.957369517  2.038287426  0.406777519  0.2481564533 -1.7125211380
961 -1.449481291 -0.290533526  1.885678714 -0.9661510749  1.3632677948
962 -2.143299973  0.012687759  0.522964352 -0.8558886313  0.2623653796
963  2.845627808 -0.278414135  0.942039847  1.9647358320 -0.6776437687
964 -0.984435645 -2.282419563 -0.163278935  1.7751683372  0.0819162331
965  1.584826003 -1.698879414  0.072442131  0.5418231299 -1.7113353198
966 -2.726530485 -0.056339071 -1.351305232 -1.6744946680 -0.2258221410
967  3.547666619 -0.581305064 -1.334928684 -1.6290650540  0.0484880906
968  0.192271632 -1.103082280  0.787675206 -0.1015281959  1.6273291007
969  3.430289847 -0.377632085  0.444580537 -0.4086968140  0.8043748646
970  0.971765884 -0.978495790  1.423304471 -0.0109817155  1.2591859753
971  0.633178581 -1.168465364 -1.347286856  0.1811053110 -2.3006441560
972  0.475961888  2.786404061  0.962978603 -0.3652528424  0.9068208831
973 -0.645858844  2.297268680  0.231786627  0.7482561302 -0.4523885748</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_ind</span>(respca,<span class="at">geom=</span><span class="st">"point"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projet_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>g3<span class="ot">&lt;-</span><span class="fu">fviz_pca_ind</span>(respca,</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">habillage =</span> gym<span class="sc">$</span>gender,   <span class="co"># variable qualitative pour colorier</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">legend.title =</span> <span class="st">"Gender"</span>,<span class="at">geom=</span><span class="st">"point"</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>g3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• fill : "Gender"
• linetype : "Gender"</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projet_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_pca_ind</span>(respca,</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">habillage =</span> gym<span class="sc">$</span>type,   <span class="co"># variable qualitative pour colorier</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">legend.title =</span> <span class="st">"Type"</span>,<span class="at">geom=</span><span class="st">"point"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• fill : "Type"
• linetype : "Type"</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projet_files/figure-html/unnamed-chunk-5-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>g1<span class="ot">&lt;-</span><span class="fu">fviz_pca_ind</span>(respca,</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">habillage =</span> gym<span class="sc">$</span>freq,   <span class="co"># variable qualitative pour colorier</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">legend.title =</span> <span class="st">"Fréquence"</span>,<span class="at">geom=</span><span class="st">"point"</span>,<span class="at">repel =</span> T)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>g1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• fill : "Fréquence"
• linetype : "Fréquence"</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projet_files/figure-html/unnamed-chunk-5-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Le graphique n’est pas très lisible et ne permet pas d’interpréter de nombreux éléments en détail. On observe néanmoins la formation de quelques groupes, même si les caractéristiques précises expliquant ces regroupements restent difficiles à identifier.</p>
<p>En colorant les individus selon le genre, le type ou la fréquence, certaines tendances apparaissent. Concernant le genre, une distinction est visible principalement sur l’axe 2 : les hommes se situent davantage du côté associé à des valeurs plus élevées de poids, taille et IMC, contrairement aux femmes.</p>
<p>En revanche, aucune tendance claire ne se dégage concernant le type, les individus étant répartis de manière trop homogène.</p>
<p>Pour la fréquence, on observe qu’elle influence surtout l’axe 1 : plus on se déplace vers la droite, plus la fréquence augmente. Cela est cohérent avec le cercle de corrélation, où l’axe 1 est associé à un nombre plus élevé de calories brûlées et à une présence plus régulière en salle, ce qui reflète logiquement une fréquence d’entraînement plus importante</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>g2<span class="ot">&lt;-</span><span class="fu">fviz_pca_var</span>(respca, <span class="at">repel=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.
ℹ The deprecated feature was likely used in the ggpubr package.
  Please report the issue at &lt;https://github.com/kassambara/ggpubr/issues&gt;.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `aes_string()` was deprecated in ggplot2 3.0.0.
ℹ Please use tidy evaluation idioms with `aes()`.
ℹ See also `vignette("ggplot2-in-packages")` for more information.
ℹ The deprecated feature was likely used in the factoextra package.
  Please report the issue at &lt;https://github.com/kassambara/factoextra/issues&gt;.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>g2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projet_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Dans le cercle de corrélation, on observe que les variables <em>fat</em> d’une part, et <em>calories</em>, <em>duration</em>, etc. d’autre part, contribuent toutes à la formation de la première dimension, mais dans des directions opposées, ce qui est cohérent avec leur relation inverse.</p>
<p>Par ailleurs, les variables <em>poids</em>, <em>la consommation d’eau</em> et <em>taille</em> influencent principalement la construction du deuxième axe factoriel</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(g2,g3,<span class="at">ncol=</span><span class="dv">2</span>, <span class="at">widths =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="fl">3.6</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• fill : "Gender"
• linetype : "Gender"</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projet_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(g2,g1,<span class="at">ncol=</span><span class="dv">2</span>, <span class="at">widths =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="fl">3.6</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Ignoring unknown labels:
• fill : "Fréquence"
• linetype : "Fréquence"</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projet_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(gym[,<span class="dv">7</span>]) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="projet_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#qqplot(gym[,7])</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(gym<span class="sc">$</span>calories[gym<span class="sc">$</span>gender <span class="sc">==</span> <span class="st">"Male"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  gym$calories[gym$gender == "Male"]
W = 0.99169, p-value = 0.005878</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(gym<span class="sc">$</span>calories[gym<span class="sc">$</span>gender <span class="sc">==</span> <span class="st">"Female"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  gym$calories[gym$gender == "Female"]
W = 0.99259, p-value = 0.02178</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(gym<span class="sc">$</span>calories)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  gym$calories
W = 0.99176, p-value = 2.982e-05</code></pre>
</div>
</div>
<p>—— On peut dire que la variable calorie suit une loi normale (APPARAMENT ON PEUT PAS RÉPONDRE À CETTE QUESTION POUR L’INSTANT CAR ON VA FAIRE LES TESTES DE NORMALITÉ EN JANVIER)</p>
<p>Chat a donné cette proposition de syntaxe donc on voit que la p-valeur est trop basse pour les hommes et les femmes donc la variable calorie n’est pas normal ——-</p>
<p>La p-valeur obtenue pour les hommes comme pour les femmes est très faible, ce qui indique que la variable <em>calories</em> ne suit pas une distribution normale dans les deux groupes</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">#test_chi2_pour tester l'indépendance entre la variabe genre et calories (quali/quanti) donc on peut pas faire un test X2</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="co">#tab&lt;- table(gym$gender, gym$calories)</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="co">#chisq.test(tab)</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="co">#t.test(calories ~ gender, data = gym) #test de student qui est élligible que si la variable calories suit une loi normal</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Assurez-vous que gender est bien un facteur</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>gym<span class="sc">$</span>gender <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(gym<span class="sc">$</span>gender)</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a><span class="co"># ANCOVA corrigée</span></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a><span class="co"># On retire weight et height car ils sont déjà contenus dans le bmi</span></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>ancova <span class="ot">&lt;-</span> <span class="fu">aov</span>(calories <span class="sc">~</span> bpm_ave <span class="sc">+</span> duration <span class="sc">+</span> fat <span class="sc">+</span> water <span class="sc">+</span> bmi <span class="sc">+</span> gender, <span class="at">data =</span> gym)</span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Affichage des résultats</span></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ancova)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df   Sum Sq  Mean Sq  F value   Pr(&gt;F)    
bpm_ave       1  8335577  8335577  2521.27  &lt; 2e-16 ***
duration      1 58891066 58891066 17812.82  &lt; 2e-16 ***
fat           1   537499   537499   162.58  &lt; 2e-16 ***
water         1   362659   362659   109.69  &lt; 2e-16 ***
bmi           1    85578    85578    25.89 4.35e-07 ***
gender        1   845986   845986   255.89  &lt; 2e-16 ***
Residuals   966  3193697     3306                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>En réalisant une ANOVA à un facteur entre la variable <em>calories brûlées</em> et le <em>genre</em>, on obtient une p-valeur très faible. Cela indique que le nombre de calories brûlées varie significativement selon le genre</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>sub1 <span class="ot">&lt;-</span> <span class="fu">subset</span>(gym, type <span class="sc">==</span><span class="st">"Yoga"</span> )</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>sub2 <span class="ot">&lt;-</span> <span class="fu">subset</span>(gym, type <span class="sc">==</span><span class="st">"HIIT"</span> )</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>sub3 <span class="ot">&lt;-</span> <span class="fu">subset</span>(gym, type <span class="sc">==</span><span class="st">"Cardio"</span> )</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>sub4 <span class="ot">&lt;-</span> <span class="fu">subset</span>(gym, type <span class="sc">==</span> <span class="st">"Strength"</span>)</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="co">#test_anova_un_facteur_pour tester l'indépendance entre la variabe genre et calories pour le type de sport=Yoga </span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>anova1 <span class="ot">&lt;-</span> <span class="fu">aov</span>(calories <span class="sc">~</span> gender, <span class="at">data =</span> sub1)</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df   Sum Sq Mean Sq F value Pr(&gt;F)
gender        1    55475   55475   0.727  0.395
Residuals   237 18093026   76342               </code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co">#test_anova_un_facteur_pour tester l'indépendance entre la variabe genre et calories pour le type de sport=HIIT</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>anova2 <span class="ot">&lt;-</span> <span class="fu">aov</span>(calories <span class="sc">~</span> gender, <span class="at">data =</span> sub2)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df   Sum Sq Mean Sq F value  Pr(&gt;F)   
gender        1   647070  647070   8.896 0.00318 **
Residuals   219 15929355   72737                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co">#test_anova_un_facteur_pour tester l'indépendance entre la variabe genre et calories pour le type de sport=Cardio </span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>anova3 <span class="ot">&lt;-</span> <span class="fu">aov</span>(calories <span class="sc">~</span> gender, <span class="at">data =</span> sub3)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df   Sum Sq Mean Sq F value Pr(&gt;F)   
gender        1   615722  615722   8.689 0.0035 **
Residuals   253 17927776   70861                  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co">#test_anova_un_facteur_pour tester l'indépendance entre la variabe genre et calories pour le type de sport=Strength</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>anova4 <span class="ot">&lt;-</span> <span class="fu">aov</span>(calories <span class="sc">~</span> gender, <span class="at">data =</span> sub4)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df   Sum Sq Mean Sq F value  Pr(&gt;F)   
gender        1   532607  532607   7.475 0.00669 **
Residuals   256 18239361   71248                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co">#test_chi2_pour tester l'indépendance entre la variabe genre et type</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>tab5 <span class="ot">&lt;-</span> <span class="fu">table</span>(gym<span class="sc">$</span>type, gym<span class="sc">$</span>gender)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(tab5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  tab5
X-squared = 1.4013, df = 3, p-value = 0.7052</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co">#test_chi2_pour tester l'indépendance entre la variabe genre et level </span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>tab6 <span class="ot">&lt;-</span> <span class="fu">table</span>(gym<span class="sc">$</span>level, gym<span class="sc">$</span>gender)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(tab6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  tab6
X-squared = 0.012838, df = 2, p-value = 0.9936</code></pre>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>